#!/usr/bin/env python3
"""Fail a PR that mints a new legacy-named thing.

Hard rule 7 of the sunset plan: never mint anything new carrying the old brand. A
service, secret, topic, env var, file or identifier named that way adds a
redirect somebody has to keep forever and spends a rename option that was already
paid for. The programme runs for weeks with ordinary feature work alongside it,
so the rule needs a gate rather than a reviewer's attention.

What it does: compares the legacy-name lines per file, by TEXT, between the tree
being built and the base tree, and fails a file that carries text the repo did
not have before. Not a count comparison — a flat or falling count can still hide
newly minted text, and a risen one can be nothing but a move. See "Why the count
is not the check" below. Decreases are the point of the programme and are
reported as progress.

Why per file rather than a repo total: a total hides an addition behind an
unrelated deletion elsewhere in the same PR, while a per-file count keeps a
within-file move (delete plus re-add) at net zero, which is most of what the
infrastructure and rewrite waves do.

A move BETWEEN files is kept at net zero too, and needs a second check to be —
the per-file count alone fails it, because the destination goes up. So a line
whose exact text the base tree already had somewhere is treated as moved rather
than minted. See :func:`_minted`.

Why against the base tree rather than a committed baseline: a baseline file goes
stale, churns on every move, and has to be regenerated by the same person the
gate is pointed at. On a ``pull_request`` the checkout is already the merge
commit, so the comparison against the base branch is exactly this PR's
contribution and there is nothing to maintain.

**The escape hatch, and the two claims it can make.** A line carrying either
marker is not counted. The gate cannot tell them apart — the pass/fail decision
never reads which one is there, and nothing that failed before passes now. They
differ only in what a reviewer has to check, which is the only thing a marker
was ever for. Put one on the line with a reason and it lands in the diff.

``legacy-name-ok`` is rule 3's hatch: something new that BEARS the old name — a
compat alias, a redirect, a test pinning the old wire format.

``legacy-name-floor`` is a line that merely NAMES something the rename will never
reach, and cannot be correct without the literal: a pasteable command, an on-disk
path, a served mirror path. Nothing is declared and the footprint does not grow.

Why a second marker rather than a convention inside the reason text. Audited at
full coverage across the seven repos: 622 markers — **340 aliases, 274 floor
mentions**, and 8 on lines that should have been reworded rather than marked at
all. Forty-four per cent of every exemption in the programme is the kind rule 3
has nothing to say about, and the only thing separating them is prose.

The two populations also grow from different work. An alias arrives when
something is renamed. A floor mention arrives whenever a document that mentions
the product's own name is EDITED — re-flowing a comment mints new text even as
the file's count falls, and a marker cannot come off a line without the literal
coming off with it. So that half of the pile is fed by maintaining documentation
rather than by sweeping the brand, and it grows for as long as the docs are
maintained. caura-daemon#136 is the shape of it in one PR: eleven exemptions,
four of them aliases, and a reviewer facing eleven undifferentiated entries
stops reading.

What this is NOT is a fix for false reasons at scale. Only 11 of the 622 (1.8%)
put alias language on a non-alias line, and 218 of the 274 floor mentions
already say "floor", "pinned" or "frozen" in their own reason text. Authors have
been drawing the distinction correctly all along; the gate has had nowhere to
record it, so it could not count on it. This makes the distinction structural.

Both are a claim someone has to stand behind, and a floor marker is falsifiable
in one move: reword the line without the old name, and if it is still correct
then the marker was false and the line should carry no marker at all.

**Why the count is not the check.** A file's total is a cheap proxy for "worth
looking at", and it is the wrong one in both directions. It fails a cross-file
move, where the destination rises and nothing was minted. And it passes a
same-file swap, where one branded line is dropped and a different, brand-new one
added in the same edit: flat total, so a count-first filter never looks at the
text and the gate reports "No new lines." Both are decided by comparing the text
instead, which is what :func:`_minted` does for every file rather than only the
ones whose tally rose.

That also closes the exempt-and-add swap, which counting genuinely cannot: mark
an existing line exempt and fill the freed slot with a new unmarked one and every
tally matches a legitimate marked alias — non-exempt flat, exempt +1, total +1 —
because the difference is *which* line carries the marker. The texts differ
though. A legitimate alias adds new EXEMPT text and no new non-exempt text, so
there is nothing to charge; the swap adds non-exempt text the repo never had.
Every newly exempted line is still printed, on the passing path too, because the
report is what made the hole visible and stays useful when the swap is deliberate.

**What this still does not enforce.** The move check pairs an addition with a
deletion by text, so it cannot know the two are the same line: adding a genuinely
new occurrence while coincidentally deleting a byte-identical one elsewhere comes
out flat and is excused. That one is identical in every number AND in every text,
so nothing here can decide it — every excused move is printed with the file whose
deletion paid for it, and a reviewer who sees an unrelated file there has found
the laundering.

Usage::

    scripts/legacy_name_ratchet.py                     # compare against configured base
    scripts/legacy_name_ratchet.py --base <tree-ish>
    scripts/legacy_name_ratchet.py --report            # current inventory only; never fails
    scripts/legacy_name_ratchet.py --report --base HEAD # inventory + change split
    scripts/legacy_name_ratchet.py --report --json      # machine-readable inventory
"""

from __future__ import annotations

import argparse
import functools
import json
import os
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path, PurePosixPath
from typing import NamedTuple, overload

# The legacy brand. Matched case-insensitively, so every casing in the tree
# counts — prose, identifiers and SCREAMING_SNAKE env names alike. This is the
# only place the literal appears in this file, and it carries the marker so the
# gate does not trip over its own pattern; excluding the file instead would leave
# a hole in the scan.
LEGACY_NAME = "memclaw"  # legacy-name-ok: the pattern this gate searches for

# Kept deliberately ugly so they are never typed by accident and always read as a
# decision rather than a formatting artifact.
EXEMPT_MARKER = "legacy-name-ok"
FLOOR_MARKER = "legacy-name-floor"

_CONFIG_PATH = "scripts/legacy_name_ratchet.json"
_CONFIG_FIELDS = frozenset(
    {
        "default_base",
        "release_please_changelogs",
        "mirror_paths",
        "mirror_manifest",
        "marker_inventory_meta_paths",
    }
)

# These files define and exercise marker syntax. Their own examples are not
# programme inventory. Repositories add rename-programme documents to the same
# analytics-only exclusion through ``marker_inventory_meta_paths``; every path
# remains fully scanned by the gate itself.
_MARKER_SYSTEM_PATHS = frozenset(
    {
        "scripts/legacy_name_ratchet.py",
        "tests/test_legacy_name_ratchet.py",
    }
)


class Config(NamedTuple):
    """The complete per-repository surface of the canonical engine."""

    default_base: str
    release_please_changelogs: bool
    mirror_paths: tuple[str, ...]
    mirror_manifest: str | None
    marker_inventory_meta_paths: tuple[str, ...]


_ACTIVE_CONFIG: Config | None = None


class _Kind(NamedTuple):
    """What the report calls one marker, and the guidance printed under it.

    A NamedTuple rather than a bare pair because ``_KINDS[marker][0]`` says
    nothing about which half it is, and the file already uses one for
    :class:`Scan`.
    """

    label: str
    guidance: tuple[str, ...]


# The markers, in the order the report lists them, with what it calls each.
# Aliases lead whether there are four of them or one: they are what rule 3 wants
# eyes on, so their position must not depend on a tally. The label carries its
# own ``(s)`` the way every other count in this file does.
#
# The gate never reads this. Both markers exempt a line identically — see
# :func:`_kind` — and the split exists purely so the report can say "4 compat
# aliases and 6 floor mentions" where it used to say "11 exemptions".
#
# **Keys must be lowercase**, or the entry is never found and its lines vanish
# from the report while still exempting. :func:`_kind` explains why.
#
# **Adding a kind is not only a line here.** The failure text at the end of
# :func:`main` is the only place the gate tells an author a marker exists at all,
# and it is written out per kind rather than driven from this table, because it
# is imperative advice addressed to someone whose build just went red and does
# not fit the same mould as the report's. A new kind wants a paragraph there too;
# omitted, it is a marker nobody discovers.
#
# Guidance is a tuple of already-wrapped lines rather than one string with
# newlines in it, for the same reason this file prints its other prose a line at
# a time: re-flowing an embedded ``\n`` is how a paragraph silently loses its
# shape, and the first line has to be joinable to a count.
_KINDS: dict[str, _Kind] = {
    EXEMPT_MARKER: _Kind(
        "compat alias(es)",
        (
            "rule 3's escape hatch, and what this report is for.",
            "Check each is a compat alias, a redirect or a pinned wire format,",
            "and not headroom for a new name:",
        ),
    ),
    FLOOR_MARKER: _Kind(
        "floor mention(s)",
        (
            "a permanent name in text, not a new declaration.",
            "Check the line cannot be correct without the literal: a pasteable",
            "command, an on-disk path, a served mirror path. If rewording it",
            "would leave it correct, the claim is false and it should carry no",
            "marker at all:",
        ),
    ),
}

# Matched as a bounded token, not a bare substring. A substring test exempts any
# line that merely contains a marker inside a longer word — "not
# legacy-name-okay to leave in" would silence a real occurrence, which is a hole
# in the gate rather than a nuisance. Case-insensitive for the same reason the
# name match is: a marker typed ``Legacy-Name-OK`` is plainly a decision, and
# failing it would be a spurious red on a line someone deliberately annotated.
#
# Bounded on BOTH sides, and the two are not the same check: the lookahead stops
# ``legacy-name-okay`` and the lookbehind stops ``somelegacy-name-ok``. Either one
# alone leaves the hole open from the other end.
#
# Neither boundary is a comment prefix — comment syntax differs across the file
# types this scans, and JSON has none at all while still being somewhere an alias
# can legitimately live.
#
# One pattern for both markers rather than one each, so those boundaries are
# stated once and cannot drift apart: the lookbehind and lookahead sit outside
# the alternation, so every marker gets both. Alternation order is not load
# bearing here because neither marker is a prefix of the other — if a third is
# ever added that IS a prefix of another, list the longer one first, since Python
# takes the first alternative that matches rather than the longest.
EXEMPT_RE = re.compile(
    rf"(?<![\w-])(?P<marker>{'|'.join(re.escape(m) for m in _KINDS)})(?=[\s:]|$)",
    re.IGNORECASE,
)


def _kind(text: str) -> str | None:
    """Which marker exempts this line, or ``None`` if none does.

    Returns the marker literal rather than its label, so the marker stays the one
    identity a kind is keyed by and :data:`_KINDS` stays the only place a label
    is written down.

    The gate's decision reads only whether this is ``None``. That is what keeps
    the two markers interchangeable at the point of failure: a line that passed
    before passes now, and a marker a reviewer thinks is the wrong KIND is still
    a marker, so mislabelling one can never turn a red build green or a green one
    red. Only the report reads which.

    **When both claims are true of one line, the alias wins.** This is not the
    degenerate case it looks like: 28 lines across the fleet name a permanent
    thing AND declare a dual-read in the same breath, e.g. an image tag whose
    repository name is frozen while its version is read from both spellings.
    Both claims are true, one line can only carry one marker, and picking by
    position on the line would make the answer depend on which end the author
    typed first.

    So precedence is :data:`_KINDS` order, which puts the alias first: an alias
    reported as a floor mention is a rule 3 decision nobody looked at, while a
    floor mention reported as an alias is one extra line in the list that most
    wants reading anyway. Under-counting the aliases is the expensive direction,
    so the tie breaks away from it.

    The lowercasing is what keeps the result a usable :data:`_KINDS` key, and it
    is load bearing rather than tidiness. A kind that does not match a key is
    still not ``None``, so the line stays exempt and the gate stays green — while
    the report, which looks the kind up to decide which list it belongs in, finds
    nothing and drops the line without a word. Exempt but unprinted is the one
    outcome this report exists to prevent.
    """
    found = {m.group("marker").lower() for m in EXEMPT_RE.finditer(text)}
    return next((marker for marker in _KINDS if marker in found), None)


def _reason(text: str, kind: str) -> str:
    """What ``kind``'s marker says on this line: the text between it and the next.

    Lives beside :func:`_kind` rather than inline in the report because the two
    have to agree about which marker owns the line, and a rule split across two
    call sites is one that eventually disagrees with itself.

    Bounded on BOTH ends, and the second bound is the one that is easy to miss.
    Slicing to end-of-line is right for the ordinary single-marker case and wrong
    the moment a line carries two: with the winning marker written first, the
    tail swallows the other marker's literal AND its reason, so the report groups
    under a key like ``dual-read alias  legacy-name-floor: the command``. That is
    not merely ugly — the reason is the grouping key, so two lines making the
    same claim stop collapsing together, which is the one thing the grouping is
    for.

    ``.lower()`` on both sides of the comparison: the pattern is
    case-insensitive, so a marker typed ``Legacy-Name-OK`` matches while ``kind``
    is always normalised. Comparing raw finds nothing and quietly degrades every
    oddly-cased line to "(no reason given)".

    Empty string when the marker is not found, which cannot happen for a line
    that :func:`_kind` classified — the caller turns it into "(no reason given)"
    either way.
    """
    matches = list(EXEMPT_RE.finditer(text))
    here = next(
        (i for i, m in enumerate(matches) if m.group("marker").lower() == kind), None
    )
    if here is None:
        return ""
    start = matches[here].end()
    stop = matches[here + 1].start() if here + 1 < len(matches) else len(text)
    return text[start:stop].lstrip(": ").strip()


# Above this many lines sharing one reason, the list is collapsed to a count.
# Four is where a homogeneous block stops being read line by line; below it the
# individual lines are still the more useful form.
_EXEMPTION_GROUP_AT = 4


def _git(args: list[str]) -> str:
    """git, with ``grep``'s no-match exit treated as an empty result.

    ``git grep`` exits 1 when nothing matched, which is the ordinary outcome for a
    clean tree rather than an error; a bad tree-ish exits 128 and is raised, so a
    mistyped base cannot read as "no matches" and quietly pass the gate.

    What exit 1 does NOT distinguish is a pathspec that matches nothing — git
    reports that the same way, with an empty stderr. That is why
    :func:`main` refuses to pass when BOTH trees come back empty.
    """
    # check=False deliberately: the return code is the signal here, not an error.
    #
    # The encoding is pinned rather than left to the locale. ``text=True`` alone
    # decodes with ``locale.getpreferredencoding()``, which is UTF-8 on the CI
    # runner but a legacy codepage on a Windows workstation — cp1255, cp1251,
    # cp1252, whatever the machine is set to. The tree has non-ASCII bytes in it
    # (em dashes in prose, accented names in fixtures), so on those machines the
    # decode raises UnicodeDecodeError inside subprocess's reader thread and the
    # script dies before it prints anything. It is not a gate failure — the gate
    # simply cannot be run locally, which is where you want to run it first.
    # ``errors="replace"`` keeps an undecodable byte from being fatal: this
    # counts occurrences of an ASCII name, so a mangled character elsewhere on
    # the line changes nothing about the match.
    proc = subprocess.run(
        args,
        capture_output=True,
        text=True,
        check=False,
        encoding="utf-8",
        errors="replace",
    )
    if proc.returncode == 0:
        return proc.stdout
    if proc.returncode == 1:
        return ""
    raise RuntimeError(
        f"{' '.join(args)} failed ({proc.returncode}): {proc.stderr.strip()}"
    )


@functools.cache
def _repo_root() -> Path:
    """The repository whose configuration and tracked tree are being scanned."""
    return Path(_git(["git", "rev-parse", "--show-toplevel"]).strip())


def _repo_path(value: object, field: str) -> str:
    """Validate one root-relative, literal repository path from the config."""
    if not isinstance(value, str):
        raise TypeError(f"{field} must contain strings")
    if not value:
        raise ValueError(f"{field} must contain non-empty strings")
    path = PurePosixPath(value)
    if (
        not path.parts
        or path.is_absolute()
        or "\\" in value
        or re.match(r"^[A-Za-z]:", value)
        or value != path.as_posix()
        or ".." in path.parts
    ):
        raise ValueError(
            f"{field} path must be normalized and repository-relative: {value!r}"
        )
    return value


def _base_ref(value: object, field: str) -> str:
    """Validate a ref before placing it in git's option-bearing argument area."""
    if not isinstance(value, str):
        raise TypeError(f"{field} must be a string")
    if not value.strip() or value != value.strip():
        raise ValueError(f"{field} must be a non-empty ref without outer whitespace")
    if value.startswith("-") or "\0" in value:
        raise ValueError(f"{field} must be a ref, not a git option")
    return value


def _repo_paths(value: object, field: str) -> tuple[str, ...]:
    """Validate one path-list field without silently accepting duplicates."""
    if not isinstance(value, list):
        raise TypeError(f"{field} must be a list")
    paths = tuple(_repo_path(item, field) for item in value)
    if len(paths) != len(set(paths)):
        raise ValueError(f"{field} must not contain duplicate paths")
    return paths


def _load_config() -> Config:
    """Read and strictly validate the five-field repository configuration."""
    path = _repo_root() / _CONFIG_PATH
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise ValueError(f"cannot read {_CONFIG_PATH}: {exc}") from exc
    if not isinstance(raw, dict):
        raise TypeError(f"{_CONFIG_PATH} must contain a JSON object")

    fields = set(raw)
    missing = sorted(_CONFIG_FIELDS - fields)
    unknown = sorted(fields - _CONFIG_FIELDS)
    if missing or unknown:
        details = []
        if missing:
            details.append(f"missing {', '.join(missing)}")
        if unknown:
            details.append(f"unknown {', '.join(unknown)}")
        raise ValueError(f"invalid {_CONFIG_PATH}: {'; '.join(details)}")

    default_base = _base_ref(raw["default_base"], "default_base")
    release_please = raw["release_please_changelogs"]
    if not isinstance(release_please, bool):
        raise TypeError("release_please_changelogs must be a boolean")

    manifest_value = raw["mirror_manifest"]
    mirror_manifest = (
        None
        if manifest_value is None
        else _repo_path(manifest_value, "mirror_manifest")
    )
    return Config(
        default_base=default_base,
        release_please_changelogs=release_please,
        mirror_paths=_repo_paths(raw["mirror_paths"], "mirror_paths"),
        mirror_manifest=mirror_manifest,
        marker_inventory_meta_paths=_repo_paths(
            raw["marker_inventory_meta_paths"], "marker_inventory_meta_paths"
        ),
    )


def _config() -> Config:
    """The config selected by :func:`main`, or a lazy one for direct helpers."""
    return _ACTIVE_CONFIG if _ACTIVE_CONFIG is not None else _load_config()


@functools.cache
def _manifest_mirrors(config: Config, root: Path) -> tuple[str, ...]:
    """Paths from the optional vendored-file manifest."""
    if config.mirror_manifest is None:
        return ()
    try:
        raw = json.loads((root / config.mirror_manifest).read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        raise ValueError(
            f"cannot read mirror_manifest {config.mirror_manifest!r}: {exc}"
        ) from exc
    if not isinstance(raw, dict):
        raise TypeError("mirror_manifest must contain a JSON object")
    return tuple(_repo_path(item, "mirror_manifest") for item in raw)


def _mirror_paths(config: Config | None = None) -> tuple[str, ...]:
    """All generated and vendored mirrors, de-duplicated in stable order."""
    selected = config or _config()
    return tuple(
        sorted(
            set(selected.mirror_paths) | set(_manifest_mirrors(selected, _repo_root()))
        )
    )


def _excluded_mirrors(config: Config | None = None) -> tuple[str, ...]:
    """Root-anchored literal exclusions used by every ordinary scan."""
    return tuple(f":(exclude,top,literal){path}" for path in _mirror_paths(config))


def _included_mirrors(config: Config | None = None) -> tuple[str, ...]:
    """The same mirrors as positive pathspecs for report-only inventory."""
    return tuple(f":(top,literal){path}" for path in _mirror_paths(config))


def _grep(
    tree: str | None,
    pathspec: str | list[str] = ":/",
    *,
    exclusions: bool = True,
) -> list[tuple[str, str, str, str | None]]:
    """``(path, lineno, text, kind)`` for every matching line.

    ``kind`` is the marker literal exempting the line, or ``None`` for a line
    that carries none — see :func:`_kind`. A kind rather than a bool because the
    report has to separate the two claims a marker can make.

    Exempt lines are returned rather than dropped so the caller can report what a
    change newly exempted — see :func:`main`.

    ``tree=None`` reads the working tree. ``-I`` skips binary files. ``--full-name``
    makes paths repo-relative whatever the working directory, which the ``:/``
    pathspec then matches against the whole repo rather than a subtree.

    ``-z`` is what makes the parse safe rather than merely usually-right. Without
    it the record is colon-separated and a colon in either the path (legal on
    Linux, which is what CI runs on) or the matched text shifts every field after
    it: the line is attributed to a path that does not exist, the real file's
    count never rises, and the gate passes while appearing to work. With ``-z``
    the fields are NUL-separated and only the ``<tree>:`` prefix is colon-joined —
    and that one is a string this function passed in, so it can be stripped by
    length instead of by searching.
    """
    args = ["git", "grep", "-I", "-i", "-n", "-z", "--full-name", "-e", LEGACY_NAME]
    if tree is not None:
        args.append(tree)
    args.append("--")
    args += [pathspec] if isinstance(pathspec, str) else pathspec
    if exclusions:
        args += _excluded_mirrors()

    prefix = f"{tree}:" if tree is not None else ""

    out: list[tuple[str, str, str, str | None]] = []
    # Records are newline-terminated (a matched line cannot contain one) and
    # their three fields are NUL-separated.
    for record in _git(args).split("\n"):
        if not record:
            continue
        parts = record.split("\0", 2)
        if len(parts) != 3:
            continue
        path, lineno, text = parts
        if prefix:
            if not path.startswith(prefix):
                continue
            path = path[len(prefix) :]
        out.append((path, lineno, text, _kind(text)))
    return out


def _changed_paths(base: str) -> set[str] | None:
    """Every path this change touched, per git. ``None`` if the diff failed.

    What selects the files the exemption report talks about. The exempt tally
    cannot do it: a change that removes one exemption and adds another in the
    same file is net zero, so a rise-based filter never looks at that file and
    the new exemption is never printed — the one thing the report exists to stop
    happening quietly. Asking git which files moved has no such blind spot.

    ``None`` rather than an empty set on failure, because the two mean opposite
    things to the caller: "could not tell" must fall back to the old tally-based
    selection, while "nothing changed" must select nothing.

    ``-z`` for the same reason :func:`_grep` passes it, and it is load bearing
    here in a way that is easy to miss. Without it git honours ``core.quotePath``
    and returns a path holding any non-ASCII byte C-quoted — ``café.py`` comes
    back as the ten characters ``"caf\\303\\251.py"``, quotes included. Every
    other path in this module is raw, because ``_grep`` reads them with ``-z``,
    so a quoted path matches nothing in ``after`` and the file drops silently out
    of the selection below. It then falls back to the risen tally alone, which
    reopens the net-zero-swap hole this function exists to close — for exactly
    the files the tree is known to contain, since ``_git`` pins UTF-8 precisely
    because there are accented names in the fixtures.
    """
    try:
        return {
            path
            for path in _git(["git", "diff", "--name-only", "-z", base]).split("\0")
            if path
        }
    except RuntimeError:
        return None


def _added_lines(base: str, path: str) -> set[int] | None:
    """Line numbers this change actually added to ``path``, per git's own diff.

    Used for the failure report only, never for the decision. The decision
    compares text because a per-line diff calls every move an addition — but the
    report has the opposite problem, and needs exactly what the diff knows.

    Without it the report spends a text-keyed budget in file order, which assumes
    the first occurrence of a text is the new one. Line order says nothing about
    that. A file holding an untouched line and a new line with identical text
    gets the untouched one named, and the real addition is never printed — the
    reader is sent to a line that has not changed, for a gate whose whole output
    is "here is the line you added".

    ``None`` on failure, and the caller falls back to naming every occurrence of
    the minted text: too many lines is a nuisance, none is a dead end.

    ``None`` rather than an empty set, because once the exemption report selects
    files by what git says changed rather than by a risen tally, an empty result
    is a real and common answer — a file this change only DELETED from adds no
    lines, and every exempt line it still holds predates the change. Collapsing
    that into the failure case would reprint the whole pile for exactly the files
    that deserve none of it, which is the bug #894 fixed, reintroduced through
    the back door.
    """
    try:
        out = _git(["git", "diff", "-U0", base, "--", _literal(path)])
    except RuntimeError:
        return None

    added: set[int] = set()
    lineno = 0
    for line in out.splitlines():
        if line.startswith("@@"):
            # ``@@ -a,b +c,d @@`` — c is where the added run starts.
            match = re.search(r"\+(\d+)", line)
            lineno = int(match.group(1)) if match else 0
        elif line.startswith("+") and not line.startswith("+++"):
            added.add(lineno)
            lineno += 1
    return added


def _literal(path: str) -> str:
    """A pathspec that means exactly this path.

    The same hazard one level up: a bare path is interpreted as a pathspec, so one
    containing ``*``, ``?`` or a leading ``:`` would match the wrong files or be
    read as pathspec magic. ``:(literal)`` disables both.
    """
    return f":(literal){path}"


def _release_please_branch() -> bool:
    """True when CI builds release-please's own PR branch.

    release-please regenerates per-package CHANGELOGs by quoting merged PR
    titles verbatim, so titles that legitimately carried the old brand
    (history — rule 2 says never edit it) resurface as lines this tally
    cannot tell from fresh minting. Only that bot's branches get the
    exemption; a human editing a CHANGELOG still answers to the gate.
    GITHUB_HEAD_REF is set by Actions on pull_request runs and absent
    locally, so local runs keep full coverage.
    """
    return os.environ.get("GITHUB_HEAD_REF", "").startswith("release-please--")


class Scan(NamedTuple):
    """One pass over a tree, and everything the gate needs from it.

    ``by_file`` maps path to the text of its non-exempt matching lines and how
    many times each appears; ``total`` is the same tally repo-wide.
    ``exempt_by_file`` is the same shape for marked lines, which are reported
    but never gated on.

    Marked lines are held per file, not as a bare repo-wide tally, because the
    removal report has to name the file a vanished line came from — the same
    context :func:`_report_excused_moves` prints, and for the same reason: a
    reviewer who cannot locate the line cannot check whether the alias survived
    the rewording. Both views are needed and both derive from this one field.

    Text is whitespace-stripped. A line that moves into a class body or a deeper
    block gets re-indented on the way, and an indentation-sensitive comparison
    would call that new text. What is being compared is whether the repo already
    had this name written this way, which indentation does not change.

    One scan rather than three: the counts the ratchet holds flat are just
    ``sum(by_file[path].values())``, so deriving them here keeps a single
    definition of "a line that counts" instead of the same rule written out in
    three places that have to agree.
    """

    by_file: dict[str, Counter[str]]
    total: Counter[str]
    exempt_by_file: dict[str, Counter[str]]

    def counts(self) -> Counter[str]:
        """Non-exempt lines per file — what the ratchet holds flat."""
        return Counter({path: sum(c.values()) for path, c in self.by_file.items()})

    def exempt(self) -> Counter[str]:
        """Marked lines per file — what the new-exemption report examines."""
        return Counter(
            {path: sum(c.values()) for path, c in self.exempt_by_file.items()}
        )


def scan(
    tree: str | None,
    pathspec: str | list[str] = ":/",
    *,
    exclusions: bool = True,
) -> Scan:
    """Read a tree once. ``tree=None`` is the working tree."""
    by_file: dict[str, Counter[str]] = {}
    total: Counter[str] = Counter()
    # Not split by kind, and it does not want to be: the per-file view only
    # SELECTS files for the report, which re-greps them and reads each line's
    # kind first-hand, and the keys are text that still contains its own marker,
    # so the kind is recoverable from the key. Splitting would be a second
    # definition of the same fact.
    exempt_by_file: dict[str, Counter[str]] = {}
    for path, _, text, kind in _grep(tree, pathspec, exclusions=exclusions):
        stripped = text.strip()
        if kind is not None:
            exempt_by_file.setdefault(path, Counter())[stripped] += 1
            continue
        by_file.setdefault(path, Counter())[stripped] += 1
        total[stripped] += 1
    return Scan(by_file, total, exempt_by_file)


def _excluded_inventory() -> Counter[str]:
    """Non-exempt legacy-name lines in mirrors excluded from the gate."""
    paths = _included_mirrors()
    if not paths:
        return Counter()
    return scan(None, list(paths), exclusions=False).counts()


def _marker_inventory(head: Scan, config: Config) -> Counter[str]:
    """Marker counts with system and declared meta paths removed from analytics."""
    excluded = _MARKER_SYSTEM_PATHS | set(config.marker_inventory_meta_paths)
    inventory: Counter[str] = Counter()
    for path, lines in head.exempt_by_file.items():
        if path in excluded:
            continue
        for text, count in lines.items():
            kind = _kind(text)
            if kind is not None:
                inventory[kind] += count
    return inventory


def _untracked_count() -> int:
    """Untracked, non-ignored files omitted by git grep's tracked-only scope."""
    return len(
        [
            path
            for path in _git(
                [
                    "git",
                    "ls-files",
                    "--others",
                    "--exclude-standard",
                    "--full-name",
                    "-z",
                    "--",
                    ":/",
                ]
            ).split("\0")
            if path
        ]
    )


def _updated_scan(before: Scan, tree: str, paths: list[str]) -> Scan:
    """Apply one commit by rescanning only its changed paths."""
    if not paths:
        return before

    by_file = before.by_file.copy()
    exempt_by_file = before.exempt_by_file.copy()
    total = before.total.copy()
    for path in paths:
        total.subtract(by_file.pop(path, Counter()))
        exempt_by_file.pop(path, None)

    changed = scan(tree, [_literal(path) for path in paths])
    by_file.update(changed.by_file)
    exempt_by_file.update(changed.exempt_by_file)
    total.update(changed.total)
    return Scan(by_file, +total, exempt_by_file)


def _transition_paths(before: str, after: str | None = None) -> list[str]:
    """Tracked paths changed between two trees, or from before to worktree."""
    args = ["git", "diff", "--name-only", "-z", "--no-renames", before]
    if after is not None:
        args.append(after)
    args.append("--")
    return [path for path in _git(args).split("\0") if path]


class _ChangeSummary(NamedTuple):
    """Gross causes behind the non-exempt count's net movement."""

    added: int
    annotated: int
    removed: int
    moved: int
    net: int


# Ordinary gate runs must stay bounded. A caller asking for --report is
# explicitly asking for the archaeology and remains uncapped.
_GATE_REPLAY_LIMIT = 64


def _only_inserts(before: str, after: str) -> bool:
    """Whether deleting one contiguous insertion from ``after`` yields ``before``."""
    inserted = len(after) - len(before)
    if inserted <= 0:
        return False
    mismatch = next(
        (
            i
            for i, (old, new) in enumerate(zip(before, after, strict=False))
            if old != new
        ),
        len(before),
    )
    return after[mismatch + inserted :] == before[mismatch:]


_LineCounts = dict[tuple[str, str], int]


def _transition_delta(
    base: Scan, head: Scan
) -> tuple[_LineCounts, _LineCounts, _LineCounts]:
    """Lines that left or entered the ratcheted and exempt populations."""
    lost = {
        (path, text): n
        for path, lines in base.by_file.items()
        for text, n in (lines - head.by_file.get(path, Counter())).items()
    }
    gained = {
        (path, text): n
        for path, lines in head.by_file.items()
        for text, n in (lines - base.by_file.get(path, Counter())).items()
    }
    gained_exempt = {
        (path, text): n
        for path, lines in head.exempt_by_file.items()
        for text, n in (lines - base.exempt_by_file.get(path, Counter())).items()
    }
    return lost, gained, gained_exempt


def _match_annotations(lost: _LineCounts, gained_exempt: _LineCounts) -> int:
    """Consume losses that gained a marker in the same transition."""
    annotated = 0
    for (destination, marked), available in sorted(gained_exempt.items()):
        candidates = sorted(
            (key for key, n in lost.items() if n and _only_inserts(key[1], marked)),
            key=lambda key: (key[0] != destination, len(marked) - len(key[1]), key),
        )
        for key in candidates:
            matched = min(available, lost[key])
            annotated += matched
            available -= matched
            lost[key] -= matched
            if not available:
                break
    return annotated


def _match_moves(lost: _LineCounts, gained: _LineCounts) -> int:
    """Consume byte-identical lines that reappeared in another file."""
    moved = 0
    for (destination, text), available in sorted(gained.items()):
        sources = sorted(
            key
            for key, n in lost.items()
            if n and key[0] != destination and key[1] == text
        )
        for key in sources:
            matched = min(available, lost[key])
            moved += matched
            available -= matched
            lost[key] -= matched
            gained[(destination, text)] -= matched
            if not available:
                break
    return moved


def _match_readditions(lost: _LineCounts, gained: _LineCounts) -> int:
    """Consume lines that left and later returned to the same file."""
    readded = 0
    for key, available in sorted(gained.items()):
        matched = min(available, lost.get(key, 0))
        readded += matched
        lost[key] = lost.get(key, 0) - matched
        gained[key] -= matched
    return readded


def _transition_summary(base: Scan, head: Scan) -> _ChangeSummary:
    """Classify one tree-to-tree transition without affecting the gate."""
    lost, gained, gained_exempt = _transition_delta(base, head)
    annotated = _match_annotations(lost, gained_exempt)
    moved = _match_moves(lost, gained)

    return _ChangeSummary(
        added=sum(gained.values()),
        annotated=annotated,
        removed=sum(lost.values()),
        moved=moved,
        net=sum(head.counts().values()) - sum(base.counts().values()),
    )


@overload
def _change_summary(
    base_ref: str,
    base: Scan,
    head: Scan,
    *,
    max_commits: None = None,
) -> _ChangeSummary: ...


@overload
def _change_summary(
    base_ref: str,
    base: Scan,
    head: Scan,
    *,
    max_commits: int,
) -> _ChangeSummary | None: ...


def _change_summary(
    base_ref: str,
    base: Scan,
    head: Scan,
    *,
    max_commits: int | None = None,
) -> _ChangeSummary | None:
    """Classify each first-parent step, falling back to the two endpoints.

    Replaying matters when a line is annotated and a later commit removes it:
    by then it is exempt, so that later edit is exemption churn rather than a
    removal from the ratcheted population. Endpoint arithmetic loses that order.

    Intermediate states are updated by scanning only the paths each commit
    changed. This retains exact chronology without re-grepping the whole tree
    per commit. A range with at most one non-empty transition has no intermediate
    state to recover and reuses the endpoint scans.

    None means a bounded caller exceeded max_commits. It must omit the split
    rather than print the cheaper endpoint classification as exact.
    """
    endpoint = _transition_summary(base, head)
    try:
        base_oid = _git(["git", "rev-parse", f"{base_ref}^{{commit}}"]).strip()
        head_oid = _git(["git", "rev-parse", "HEAD^{commit}"]).strip()
        rev_list_args = ["git", "rev-list", "--first-parent", "--reverse"]
        if max_commits is not None:
            rev_list_args.append(f"--max-count={max_commits + 1}")
        rev_list_args.append(f"{base_oid}..{head_oid}")
        commits = _git(rev_list_args).splitlines()
        if max_commits is not None and len(commits) > max_commits:
            return None
        transitions: list[tuple[str, list[str]]] = []
        previous = base_oid
        for commit in commits:
            parent = _git(["git", "rev-parse", f"{commit}^1"]).strip()
            if parent != previous:
                return endpoint
            transitions.append((commit, _transition_paths(previous, commit)))
            previous = commit
        if previous != head_oid:
            return endpoint

        worktree_paths = _transition_paths("HEAD")
        if sum(bool(paths) for _, paths in transitions) + bool(worktree_paths) <= 1:
            return endpoint

        # Annotation means a marker was added without first removing the line,
        # so it is paired only inside one transition. A move can be written as
        # either delete-then-add or copy-then-delete, so residual gains and
        # losses wait for a counterpart across transitions. Same-path returns
        # are add/remove churn rather than moves and take precedence.
        lost_pool: _LineCounts = {}
        gained_pool: _LineCounts = {}
        annotated = moved = readded = 0
        current = base
        replay_steps: list[tuple[str | None, list[str]]] = list(transitions)
        if worktree_paths:
            replay_steps.append((None, worktree_paths))
        for index, (tree, paths) in enumerate(replay_steps):
            if tree is None or index == len(replay_steps) - 1:
                following = head
            else:
                following = _updated_scan(current, tree, paths)

            lost, gained, gained_exempt = _transition_delta(current, following)
            annotated += _match_annotations(lost, gained_exempt)
            for key, count in lost.items():
                lost_pool[key] = lost_pool.get(key, 0) + count
            for key, count in gained.items():
                gained_pool[key] = gained_pool.get(key, 0) + count
            readded += _match_readditions(lost_pool, gained_pool)
            moved += _match_moves(lost_pool, gained_pool)
            current = following
    except (OSError, RuntimeError):
        return endpoint

    return _ChangeSummary(
        added=readded + sum(gained_pool.values()),
        annotated=annotated,
        removed=readded + sum(lost_pool.values()),
        moved=moved,
        net=sum(head.counts().values()) - sum(base.counts().values()),
    )


def _move_label(n: int) -> str:
    return "excused move" if n == 1 else "excused moves"


def _mint_budget(head_total: Counter[str], base_total: Counter[str]) -> Counter[str]:
    """How many of each text the repo actually gained — the whole charge available.

    Computed once for the run and spent down by :func:`_minted`, because the
    charge is a repo-wide quantity and the files that can claim it are counted
    one at a time. Recomputing it per file hands every destination the same
    budget: delete one copy of a line from A, add one to each of B and C, and
    both B and C independently look like the only mint of a text the repo gained
    once — two failures reported for one addition, and one of them a move.
    """
    return +Counter(
        {text: n - base_total.get(text, 0) for text, n in head_total.items()}
    )


def _minted(
    path: str,
    head_by_file: dict[str, Counter[str]],
    base_by_file: dict[str, Counter[str]],
    budget: Counter[str],
) -> tuple[Counter[str], Counter[str]]:
    """``(minted, moved)`` for ``path``: text the repo did not have, and text it did.

    Spends ``budget`` — see :func:`_mint_budget`. Callers must iterate paths in a
    stable order: when a text lands in several files and the repo gained fewer
    copies than that, which destination is charged is arbitrary but the count is
    not, and an arbitrary-but-unstable answer would flake.

    Per-file counting is right and the module docstring's defence of it stands: a
    repo total hides a real addition behind an unrelated deletion elsewhere. But
    it only keeps a move at net zero *within* one file. Move a branded line from
    A to B and B goes ``0 -> 1`` while A drops, so the gate fails a change that
    minted nothing (#882).

    That mattered more than the spurious red, because the remedy the failure text
    offered was an exemption, and none of the three reasons rule 3 recognises —
    compat alias, redirect, pinned wire format — describes a move. The only way
    past the gate was to write a reason that was not true, into the one
    annotation whose whole value is that its reasons are true.

    So a move is recognised here rather than annotated away. A line is a move
    when the repo-wide count of that exact text did not go up: the name existed,
    in those words, and now sits somewhere else. It is minted when the count did
    go up, which no rearrangement can produce. Both shapes are covered, including
    a line moving between two files that both already exist — the likelier shape
    during a consolidation wave, and the one ``--find-renames`` cannot see.

    Strictness is unchanged for genuinely new text: a new name has no matching
    deletion to pair with, so its repo-wide count rises and it fails.

    **What text-matching cannot decide, and why it is reported instead.** The
    pairing is by text, not by provenance — nothing here knows that the deletion
    it paired with is the *same* line. A change that adds a genuinely new
    occurrence in one file while coincidentally deleting a byte-identical line
    somewhere unrelated comes out flat, and the new one is excused.

    No count fixes that, for the same reason the exempt-and-add swap below is not
    fixable: the two cases are identical in every number, and differ only in
    intent. ``--find-renames`` does not settle it either — it answers a narrower
    question and misses the common shape entirely.

    So it takes the same answer as the swap: every excused move is printed, on
    the passing path, with the base file whose deletion paid for it. A laundered
    mint stays visible in the CI log even though the gate passes, which is the
    most a text comparison can honestly offer.
    """
    new_here = head_by_file.get(path, Counter()) - base_by_file.get(path, Counter())

    minted: Counter[str] = Counter()
    moved: Counter[str] = Counter()
    for text, added_here in sorted(new_here.items()):
        # A file can gain two copies of a line the repo only gained one of: one
        # moved in, one is new. Split the tally rather than picking a side, and
        # take the charge out of the shared budget so the next file cannot be
        # charged for the same addition.
        charge = min(added_here, budget[text])
        budget[text] -= charge
        minted[text] = charge
        moved[text] = added_here - charge
    return +minted, +moved  # unary plus drops the zero entries


def _report_excused_moves(
    excused: dict[str, Counter[str]],
    base_by_file: dict[str, Counter[str]],
    head_by_file: dict[str, Counter[str]],
) -> None:
    """Name every line the move check let through, and what paid for it.

    The counterpart to :func:`_report_new_exemptions`, for the same reason and
    with the same honesty. Pairing an addition with a deletion by text cannot
    know the two are the same line, so a change that adds a genuinely new
    occurrence while coincidentally deleting a byte-identical one elsewhere comes
    out flat and is excused. No count separates that from a real move — they are
    identical in every number — so it is reported rather than adjudicated.

    Printed on the passing path, because passing is the only path this takes.
    Naming the base file whose deletion paid for each one is what makes it
    checkable: a reviewer who sees an unrelated file named there has found a
    laundered mint, and nothing else in CI would have shown it.

    A source is a file whose count of that text actually WENT DOWN, not merely
    one that had it. Every file holding an unchanged copy also contains the text,
    so listing on containment names bystanders as sources — and since the list is
    truncated, an alphabetically earlier bystander can push the real source out of
    view entirely. That turns the one output a reviewer is meant to check into
    noise, which is worse than not printing it.
    """
    if not excused:
        return

    total = sum(sum(c.values()) for c in excused.values())
    print(f"{total} line(s) treated as moved rather than added — the same text left")
    print(
        "another file in this change. Check the pairing is real and not a coincidence:"
    )
    for path in sorted(excused):
        for text, n in sorted(excused[path].items()):
            came_from = sorted(
                p
                for p, c in base_by_file.items()
                if p != path and c[text] > head_by_file.get(p, Counter())[text]
            )
            print(f"  {path}: {'x' + str(n) + ' ' if n > 1 else ''}{text[:80]}")
            print(f"      was in: {_truncated(came_from)}")
    print()


def _truncated(paths: list[str]) -> str:
    """Render a path list for a report line, capped so one line stays one line.

    Shared by both reports that name files, so the cap and the empty-list wording
    cannot drift apart between them. The cap is what forces those reports to list
    only files that genuinely changed rather than every file containing the text:
    once the list is truncated, a bystander can displace the real source.
    """
    shown = ", ".join(paths[:3]) or "an unknown file"
    return shown + (f" (+{len(paths) - 3} more)" if len(paths) > 3 else "")


def _report_removed_exemptions(
    base_by_file: dict[str, Counter[str]], head_by_file: dict[str, Counter[str]]
) -> None:
    """Name every exempt line this change removed. Reports; never fails.

    The other half of :func:`_report_new_exemptions`, and the gap that let a
    demonstrated data-loss change pass both required gates green.

    Either marker means "the ratchet may ignore this line". Neither has ever
    meant "this line is protected", and nothing enforced that reading — but a
    marker looks like protection, so lines carrying one were treated as
    handled. Deleting one *lowers* a file's non-exempt count, which the ratchet
    reports as progress. A sweep over two plugin files removed a dual-read alias
    that decides which ``.env`` keys survive a redeploy; ratchet and sentinel
    both exited 0. Three of the aliases involved already carried this marker.

    Why this reports rather than fails, which was measured rather than assumed:
    across the last 400 commits, seven removed a marked line and **none** was a
    genuine removal of protection. Every one reworded or consolidated markers
    while keeping the alias — one collapsed six into one. A failing rule keyed on
    text identity would have produced seven false positives and no true ones, and
    a rule keyed on per-file counts would have failed the consolidation too.
    Nothing textual separates "consolidated the alias" from "deleted the alias";
    that judgement is irreducibly human, so this hands a human the fact rather
    than guessing.

    **What to do when this fires.** Confirm the protection still exists in some
    form. If the line was reworded or merged, nothing is wrong. If it is simply
    gone, the dependant it existed for is now broken and nothing else in CI will
    say so. Anything whose removal breaks an already-installed user belongs in
    ``do_not_touch_sentinel.py``, which pins exact text and does fail — this
    marker is not a substitute for that and never was.

    Each line is printed with the base-tree file it left, because "confirm what
    it stood for still exists" is not answerable from the text alone — the reader
    needs somewhere to look, and short markers plausibly live in more than one
    file. Sources are the files whose count for that text actually dropped, not
    every file that happens to contain it: listing on containment would name
    untouched bystanders, and since the list is truncated a bystander can push
    the real source out of view. Same rule, and same reason, as
    :func:`_report_excused_moves`.

    **Counted per file, not as a repo-wide net**, which is the difference
    between reporting this incident and missing it. A repo-wide ``before -
    after`` cancels a deletion against any byte-identical exempt line added
    anywhere else in the same change, and the motivating incident was a *sweep*
    — the shape most likely to delete an alias in one file while writing
    something identical in another. Netting three losses against two unrelated
    gains prints "1", names the file that lost three, and reads as the mildest
    possible version of the worst case. Losses are therefore summed gross,
    across only the files whose own count fell.

    Gross counting surfaces one case netting hid: text that left one file and
    appeared in another, which is usually a move and usually benign. That is
    reported rather than suppressed — a move is exactly the "reworded or
    consolidated" case a human is being asked to confirm — but the destination
    is named on the same line, so the benign reading is available without
    grepping for it. Suppressing it instead would restore the blind spot.
    """
    # text -> {path: how many left THAT path}. Gains elsewhere never subtract.
    drops: dict[str, Counter[str]] = {}
    for path, counts in base_by_file.items():
        head_counts = head_by_file.get(path, Counter())
        for text, n_base in counts.items():
            lost = n_base - head_counts[text]
            if lost > 0:
                drops.setdefault(text, Counter())[path] = lost
    if not drops:
        return

    n = sum(sum(c.values()) for c in drops.values())
    # Not split by kind, unlike the new-exemption report. The populations are the
    # other way round here — seven removals across four hundred commits, against
    # eleven new exemptions in a single PR — so the wall this list can become is
    # hypothetical, and a split would buy nothing a reader cannot see from the
    # marker still sitting in each printed line. The guidance covers both kinds
    # instead, since a floor mention has no alias to survive and telling a reader
    # to look for one would be exactly the false reason this marker split exists
    # to stop. Worth revisiting if the removal rate ever approaches the other's.
    print(
        f"\n{n} exempt line(s) removed by this change. A marker marks a line the\n"
        "ratchet ignores, NOT a line that is protected — deleting one lowers the\n"
        "count and reads as progress. Confirm what each one stood for still exists\n"
        "in some form — the alias it declared, or the text that could not be\n"
        "correct without the name:"
    )
    for text, per_file in sorted(drops.items()):
        count = sum(per_file.values())
        suffix = f"  (x{count})" if count > 1 else ""
        print(f"  {text.strip()[:100]}{suffix}")
        print(f"      was in: {_truncated(sorted(per_file))}")
        gained = sorted(
            p
            for p, c in head_by_file.items()
            if c[text] > base_by_file.get(p, Counter())[text]
        )
        if gained:
            where = _truncated(gained)
            print(f"      identical text added in: {where} — likely a move")


def _report_new_exemptions(
    before: Counter[str], after: Counter[str], base: str
) -> None:
    """Name every exempt line this change wrote, whether or not it fails.

    The one thing a count-based ratchet cannot decide for itself, and the reason
    this report exists. Marking an existing line exempt lowers a file's
    non-exempt count by one, which is exactly enough headroom to add a new
    unmarked occurrence in the same file and come out flat.

    No count separates that from the legitimate case. Both look identical per
    file — non-exempt flat, exempt up one, total up one — because the difference
    is *which* line carries the marker, not how many do.

    The **texts** are not identical, though, and since :func:`_minted` compares
    those the swap now fails rather than passing quietly: a legitimate alias adds
    exempt text and nothing chargeable, while the swap adds non-exempt text the
    repo never had. This report is no longer the only thing standing between that
    move and a green tick.

    It is still printed, on the passing path as well. An exemption is the move
    that buys headroom, and a deliberate one — an alias landing in the same PR as
    unrelated work — should never be made quietly even when it is legitimate.

    Which is why the list is filtered to the lines this change actually wrote,
    rather than every exempt line the file happens to hold. Re-greping and
    printing all of them puts a file's whole accumulated pile under a header
    counting one, sends the reader to lines that are not in the diff, and reads
    as self-contradictory — which invites distrusting the total rather than the
    list. Phase 5's dual-read wave is exactly the change that builds those piles,
    so every later PR touching those files would reprint them. A reader who
    learns the list is mostly noise stops reading it, and that is the failure
    this report exists to prevent.

    **Git decides both halves.** It selects the lines, and it also selects the
    files. Selecting files by a risen exempt tally leaves a hole: remove one
    exemption and add another in the same file and the tally is flat, so the file
    is never examined and the new exemption is never printed. The gate still
    catches the dangerous form of that — un-marking a line raises the non-exempt
    count and :func:`_minted` charges the text — but a brand-new reason nobody is
    pointed at is precisely what this report exists to prevent, and during a
    dual-read wave a one-for-one swap inside a file already full of exemptions is
    unremarkable in a diff.

    The tally is kept only as the fallback for when git cannot answer, since a
    selection that is too narrow beats one that is arbitrary.

    **Split by kind, because one list of eleven is not a signal.** This is the
    only place the difference between the two markers is read. Floor mentions
    outnumber aliases because they accrue from editing documentation rather than
    from renaming anything — caura-daemon#136 landed eleven in one PR, four of
    them aliases — so undifferentiated they are a wall a reviewer scrolls past,
    which is the same failure the reason-grouping below prevents, one level up.

    This is a better signal, not a quieter one: nothing is dropped, the totals
    are unchanged, and both kinds are still printed in full with their reasons.
    """
    # Files git says this change touched, narrowed to those that hold an exempt
    # line at all. The union with the risen-tally set is belt and braces: when
    # ``changed`` is available it already contains every risen file, and when it
    # is ``None`` the tally is all there is.
    changed = _changed_paths(base)
    risen = {p for p, n in after.items() if n > before.get(p, 0)}
    paths = risen if changed is None else {p for p in after if p in changed} | risen
    if not paths:
        return

    # Grouped by kind, then by reason. Reason-grouping is there because the wall
    # is the failure mode: a dual-read wave exempts dozens of lines carrying one
    # identical reason, and at that length the list stops being read — which
    # costs exactly the thing it is for, since the swap this report exists to
    # expose shows up as the ONE reason that does not match its neighbours.
    # Collapsing the repeats is what makes the odd one visible instead of burying
    # it on line forty. Kind-grouping is the same argument one level up: a floor
    # mention's reason never matches an alias's, so mixing them puts a permanent
    # wall between the aliases and the reader.
    by_kind: dict[str, dict[str, list[tuple[str, str, str]]]] = {}
    shown_total = 0
    listed_paths: set[str] = set()
    unfiltered: list[str] = []
    for path in sorted(paths):
        here = [
            (lineno, text.strip(), kind)
            for _, lineno, text, kind in _grep(None, pathspec=_literal(path))
            if kind is not None
        ]
        if not here:
            continue
        # git decides which of the file's lines this change is responsible for.
        # An existing line that gains a marker is a rewrite, so git calls it
        # added and it stays in — which matters, because that is the headroom
        # move this report exists to expose.
        touched = _added_lines(base, path)
        if touched is None:
            # Diff unreadable. Falling back to every exempt line in the file
            # rather than to silence, on the same trade the offender report
            # makes below: too many lines is a nuisance and none is a dead end.
            # Named out loud, though, because unlike below this report puts a
            # number on its own list.
            picked = here
            unfiltered.append(path)
        else:
            picked = [(n, t, k) for n, t, k in here if int(n) in touched]
        # Empty is now a real answer rather than a failure — a file this change
        # only deleted from, or touched somewhere other than its exempt lines,
        # adds nothing and every marker it holds predates the change. Printing
        # them would be #894 reintroduced through the file-selection door, which
        # is the specific risk of selecting on the diff rather than the tally.
        if not picked:
            continue
        shown_total += len(picked)
        listed_paths.add(path)
        for lineno, stripped, kind in picked:
            tail = _reason(stripped, kind)
            by_kind.setdefault(kind, {}).setdefault(
                tail.strip() or "(no reason given)", []
            ).append((path, lineno, stripped))

    # Nothing survived the per-line filter: every candidate file holds only
    # exemptions that predate this change. Silence is right — the previous
    # version could not reach here, because a risen tally guaranteed something
    # to print.
    if not by_kind:
        return

    # Both counted while picking rather than derived from ``by_kind`` afterwards,
    # so neither tracks the shape of that dict — and so the header stays a count
    # of what was PICKED rather than of what was successfully classified. The two
    # are the same number today and structurally cannot differ, since
    # :func:`_kind` only ever returns a :data:`_KINDS` key. If they ever did, a
    # header larger than the sections beneath it is the visible symptom, which is
    # worth more than an agreement enforced by construction.
    print(
        f"{shown_total} exempt line(s) written by this change in "
        f"{len(listed_paths)} file(s) —"
    )

    # In ``_KINDS`` order rather than by size, so aliases lead even when the
    # mentions outnumber them — which is the usual case and the reason for the
    # split.
    present = [
        (marker, sum(len(lines) for lines in by_kind[marker].values()))
        for marker in _KINDS
        if marker in by_kind
    ]
    if len(present) > 1:
        # The line the split exists for. Skipped when only one kind is present,
        # where it would only restate the section header underneath it.
        print(", ".join(f"{n} {_KINDS[marker].label}" for marker, n in present) + ".")
    if unfiltered:
        named = ", ".join(unfiltered[:4]) + (
            f" (+{len(unfiltered) - 4} more)" if len(unfiltered) > 4 else ""
        )
        print(
            f"  (diff unreadable for {len(unfiltered)} file(s): {named} — every "
            "exempt line they hold is listed, so some may predate this change)"
        )

    for marker, n in present:
        # ``spec``, not ``kind``: ``kind`` is the marker literal a few lines up,
        # and one name for two types inside one function costs the reader a
        # lookup at every use.
        spec = _KINDS[marker]
        print(f"\n{n} {spec.label} — {spec.guidance[0]}")
        for line in spec.guidance[1:]:
            print(line)
        by_reason = by_kind[marker]
        for reason, lines in sorted(
            by_reason.items(), key=lambda kv: (-len(kv[1]), kv[0])
        ):
            if len(lines) <= _EXEMPTION_GROUP_AT:
                for path, lineno, stripped in lines:
                    print(f"  {path}:{lineno}: {stripped[:100]}")
                continue
            files = sorted({path for path, _, _ in lines})
            shown = ", ".join(files[:4]) + (
                f" (+{len(files) - 4} more)" if len(files) > 4 else ""
            )
            print(f"  {len(lines)}x  {reason[:80]}")
            print(f"      in {len(files)} file(s): {shown}")
    print()


def _present_display(head: Counter[str], mirrors: Counter[str]) -> str:
    """Human-only representation: JSON deliberately exposes no numeric column."""
    return (
        f"{sum(head.values()) + sum(mirrors.values())} lines across "
        f"{len(head) + len(mirrors)} files"
    )


def _report_payload(
    head_scan: Scan,
    mirrors: Counter[str],
    markers: Counter[str],
    untracked: int,
) -> dict[str, object]:
    """The inventory contract, including which values may cross repo boundaries.

    ``present`` is a display string rather than a numeric pair on purpose. A
    machine caller gets one fleet-summable column, ``headline``; it cannot
    accidentally select and sum ``present.lines`` because that field does not
    exist. Mirrors remain available as an explicitly non-aggregatable diagnostic
    for audit and debugging.
    """
    head = head_scan.counts()
    no_sum = {
        "allowed": False,
        "error": "per-repository diagnostic may overlap authored content in other repositories",
    }
    return {
        "schema": "legacy-name-ratchet-report/v1",
        "headline": {
            "name": "gated",
            "aggregation": {"allowed": True, "operation": "sum"},
            "lines": sum(head.values()),
            "files": len(head),
            "by_file": dict(sorted(head.items())),
        },
        "diagnostics": {
            "present": {
                "aggregation": no_sum,
                "display": _present_display(head, mirrors),
            },
            "mirrors": {
                "aggregation": no_sum,
                "lines": sum(mirrors.values()),
                "files": len(mirrors),
                "by_file": dict(sorted(mirrors.items())),
            },
        },
        "marker_inventory": {
            "counts": {marker: markers[marker] for marker in _KINDS},
            "excluded_meta_paths": list(_config().marker_inventory_meta_paths),
            "system_paths_excluded": sorted(_MARKER_SYSTEM_PATHS),
        },
        "scope": {
            "tracked_files_only": True,
            "untracked_files_omitted": untracked,
        },
        "change": None,
    }


def _print_inventory(
    head_scan: Scan,
    mirrors: Counter[str],
    markers: Counter[str],
    untracked: int,
) -> None:
    """Render the same inventory contract for a person."""
    head = head_scan.counts()
    print(
        f"{sum(head.values())} lines across {len(head)} files "
        "(gated headline; sum across repositories)"
    )
    for path, count in sorted(head.items(), key=lambda item: (-item[1], item[0])):
        print(f"  {count:>4}  {path}")

    if mirrors:
        print(
            f"Excluded from the count above: {sum(mirrors.values())} "
            f"line(s) in {len(mirrors)} mirror(s), gated where authored."
        )
        for path, count in sorted(
            mirrors.items(), key=lambda item: (-item[1], item[0])
        ):
            print(f"  {count:>4}  {path}")
    print(
        f"Present in the tree: {_present_display(head, mirrors)}. "
        "Per-repository diagnostic; never sum across repositories."
    )

    marker_summary = ", ".join(
        f"{markers[marker]} {_KINDS[marker].label}" for marker in _KINDS
    )
    print(
        f"Marker inventory: {marker_summary}. Excludes gate code/tests and "
        f"{len(_config().marker_inventory_meta_paths)} declared meta path(s)."
    )
    print(f"Scope: tracked files only; {untracked} untracked file(s) omitted.")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Ratchet on lines carrying the legacy brand."
    )
    parser.add_argument(
        "--base",
        help="tree-ish to compare against (gate default comes from repository config)",
    )
    parser.add_argument(
        "--report",
        action="store_true",
        help="print current inventory; add --base for a change split; exit 0",
    )
    parser.add_argument(
        "--json", action="store_true", help="emit --report as machine-readable JSON"
    )
    args = parser.parse_args()
    if args.json and not args.report:
        parser.error("--json requires --report")

    global _ACTIVE_CONFIG
    try:
        _ACTIVE_CONFIG = _load_config()
        head_scan = scan(None)
        mirrors = _excluded_inventory() if args.report else Counter()
        markers = _marker_inventory(head_scan, _ACTIVE_CONFIG)
        untracked = _untracked_count() if args.report else 0
    except (OSError, RuntimeError, TypeError, ValueError) as exc:
        print(exc, file=sys.stderr)
        return 2

    head = head_scan.counts()
    payload: dict[str, object] | None = None
    if args.report:
        payload = _report_payload(head_scan, mirrors, markers, untracked)
        if not args.json:
            _print_inventory(head_scan, mirrors, markers, untracked)
        if args.base is None:
            if args.json:
                print(json.dumps(payload, indent=2, sort_keys=True))
            return 0

    # A bad base must still be exit 2 for the gate. In report mode it only makes
    # the explicitly requested change split unavailable; inventory stays valid.
    base_ref = args.base if args.base is not None else _ACTIVE_CONFIG.default_base
    try:
        base_ref = _base_ref(
            base_ref,
            "--base" if args.base is not None else "default_base",
        )
        base_scan = scan(base_ref)
    except (OSError, RuntimeError, TypeError, ValueError) as exc:
        if args.report:
            message = f"Change from {base_ref} unavailable: {exc}"
            if args.json:
                assert payload is not None
                payload["change"] = {
                    "available": False,
                    "base": base_ref,
                    "error": str(exc),
                }
                print(json.dumps(payload, indent=2, sort_keys=True))
            print(message, file=sys.stderr)
            return 0
        print(exc, file=sys.stderr)
        return 2

    base = base_scan.counts()

    if args.report:
        assert payload is not None
        try:
            report_summary = _change_summary(base_ref, base_scan, head_scan)
        except Exception as exc:  # noqa: BLE001
            # The inventory above is still valid. Its documented exit-0 contract
            # must not depend on optional chronology reporting staying healthy.
            payload["change"] = {
                "available": False,
                "base": base_ref,
                "error": str(exc),
            }
            if args.json:
                print(json.dumps(payload, indent=2, sort_keys=True))
            print(f"Change from {base_ref} unavailable: {exc}", file=sys.stderr)
            return 0
        payload["change"] = {
            "available": True,
            "base": base_ref,
            "added": report_summary.added,
            "annotated": report_summary.annotated,
            "removed": report_summary.removed,
            "moved": report_summary.moved,
            "net": report_summary.net,
        }
        if args.json:
            print(json.dumps(payload, indent=2, sort_keys=True))
        else:
            print(
                f"Change from {base_ref}: {report_summary.added} added, "
                f"{report_summary.annotated} annotated, "
                f"{report_summary.removed} removed, "
                f"{report_summary.moved} {_move_label(report_summary.moved)} "
                f"({report_summary.net:+d} net)."
            )
        return 0

    if not head and not base:
        # A pathspec that matches nothing exits 1 with an empty stderr, exactly
        # like a clean tree — so a broken scan reads as "nothing to report" and
        # the gate passes every PR from then on, silently, for the rest of the
        # programme. Both trees empty is either that or a finished migration,
        # and both want a human.
        print(
            f"Found no '{LEGACY_NAME}' lines in either tree.\n"
            "Either the pattern or the pathspec is broken — in which case this gate has\n"
            "been passing without checking anything — or the migration is complete and\n"
            "this gate should be deleted along with the last of the old names."
        )
        return 1

    head_by_file, base_by_file = head_scan.by_file, base_scan.by_file
    budget = _mint_budget(head_scan.total, base_scan.total)

    grown = {}
    excused: dict[str, Counter[str]] = {}
    generated_changelogs: list[str] = []
    release_branch = (
        _ACTIVE_CONFIG.release_please_changelogs and _release_please_branch()
    )
    # Sorted: the budget is spent as files are visited, so the order decides which
    # destination is charged when one text lands in several. Arbitrary is fine;
    # unstable is not.
    for path in sorted(head):
        if release_branch and path.rsplit("/", 1)[-1].upper().startswith("CHANGELOG"):
            if head[path] > base.get(path, 0):
                generated_changelogs.append(path)
            continue
        before, n = base.get(path, 0), head[path]
        # Deliberately NOT gated on ``n > before``. A file that drops one branded
        # line and adds a different, brand-new one in the same edit comes out
        # flat, and a count-first filter skips it before anything looks at the
        # text — so the new name is never surfaced and the gate reports "No new
        # lines." Comparing the text is what catches it; the count was only ever
        # a cheap proxy for "worth looking at", and it is the wrong one.
        minted, moved = _minted(path, head_by_file, base_by_file, budget)
        if moved:
            excused[path] = moved
        if minted:
            grown[path] = (before, n, minted)

    _report_new_exemptions(base_scan.exempt(), head_scan.exempt(), base_ref)
    _report_removed_exemptions(base_scan.exempt_by_file, head_scan.exempt_by_file)
    _report_excused_moves(excused, base_by_file, head_by_file)

    if generated_changelogs:
        print(
            f"{len(generated_changelogs)} generated CHANGELOG file(s) exempt on this "
            "release-please branch (titles quoted from history):"
        )
        for path in sorted(generated_changelogs):
            print(f"  {path}")

    if not grown:
        try:
            gate_summary = _change_summary(
                base_ref,
                base_scan,
                head_scan,
                max_commits=_GATE_REPLAY_LIMIT,
            )
        except Exception as exc:  # noqa: BLE001
            # The gate decision is already made; optional reporting cannot turn
            # this passing input into an infrastructure failure.
            print(
                "Gate passes: no new lines currently fail it. "
                f"Change split unavailable: {exc}"
            )
            return 0
        if gate_summary is None:
            print(
                "No new lines fail the gate. Change split omitted: the range exceeds the "
                f"{_GATE_REPLAY_LIMIT}-commit gate replay limit; run --report "
                f"--base {base_ref} for the exact split."
            )
            return 0
        if gate_summary.added:
            print(
                "Gate passes: no new lines currently fail it. Range history: "
                f"{gate_summary.added} added, "
                f"{gate_summary.annotated} annotated, "
                f"{gate_summary.removed} removed, "
                f"{gate_summary.moved} {_move_label(gate_summary.moved)} "
                f"({gate_summary.net:+d} net)."
            )
        elif gate_summary.annotated or gate_summary.removed or gate_summary.moved:
            print(
                f"No new lines. {gate_summary.annotated} annotated, "
                f"{gate_summary.removed} removed, {gate_summary.moved} "
                f"{_move_label(gate_summary.moved)} "
                f"({gate_summary.net:+d} net)."
            )
        else:
            print("No new lines.")
        return 0

    print(f"This change adds the legacy name in {len(grown)} file(s).\n")
    for path, (before, after, minted) in sorted(grown.items()):
        # A flat or falling count can still fail: what failed is the text, not the
        # tally, and saying so stops the reader arguing with the arithmetic. Flat
        # and falling are said separately because they are different sentences —
        # calling a count that dropped "unchanged" invites exactly the argument
        # the note exists to head off.
        if after > before:
            note = ""
        elif after == before:
            note = ", count unchanged — the text is new"
        else:
            note = ", count fell — the text is new"
        print(f"  {path}  ({before} -> {after}{note})")
        # Lines carrying minted text AND actually added by this change. Both
        # halves are needed. Without the text filter the report names every
        # branded line in the file; without the diff it names the first line
        # holding the text, which in a file that already had one is a line
        # nobody touched.
        added = _added_lines(base_ref, path)
        candidates = [
            (lineno, text.strip())
            for _, lineno, text, kind in _grep(None, pathspec=_literal(path))
            if kind is None and text.strip() in minted
        ]
        shown = (
            candidates
            if added is None
            else [(n, t) for n, t in candidates if int(n) in added]
        )
        # Falling back to every occurrence rather than to silence: if the diff
        # could not be read, too many lines is a nuisance and none is a dead end.
        #
        # The ``or candidates`` also covers an empty-but-successful diff. Unlike
        # the exemption report, silence is NOT right here: this branch only runs
        # for a file that minted text the repo never had, so something was added
        # and an empty intersection means the two disagree. Naming every
        # occurrence keeps a real offender on screen.
        shown = shown or candidates
        for lineno, stripped in shown:
            print(f"      {lineno}: {stripped[:110]}")

        # When a change adds several identical lines and only some are minted,
        # every one of them is a line this change added and they cannot be told
        # apart — that is what identical means. Naming one would be a guess
        # dressed as a finding, so all are printed and the split is stated.
        for text, new in sorted(minted.items()):
            here = sum(1 for _, t in shown if t == text)
            if here > new:
                print(
                    f"      ^ {here} added lines share this text; {new} new, "
                    f"{here - new} moved in from elsewhere — identical, so which is which"
                    " cannot be told apart"
                )
    print(
        f"\nRule 7 of the sunset plan: mint nothing new named '{LEGACY_NAME}'. Every one adds a\n"
        "redirect to keep forever and spends a rename option. Use the Caura name instead.\n\n"
        "A line moved here from another file is not this: text the base tree already\n"
        "had somewhere is recognised as a move and does not fail. Every line above is\n"
        "text this repo did not have before, so no rearrangement produced it.\n\n"
        "If the addition is deliberate — a compat alias, a redirect, a test pinning the old\n"
        f"wire format, all of which rule 3 requires — append '{EXEMPT_MARKER}: <reason>' to the\n"
        "line. It is then exempt, and the reason is visible in the diff.\n\n"
        "If instead the line only NAMES something the rename will never reach, and cannot\n"
        "be correct without the literal — a pasteable command, an on-disk path, a served\n"
        f"mirror path — append '{FLOOR_MARKER}: <reason>' instead. Identical exemption,\n"
        "different claim: nothing is declared there, so it is counted apart and the\n"
        "aliases stay readable. Check the claim before you make it — if rewording the\n"
        "line would leave it correct, reword it rather than marking it."
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
