#!/usr/bin/env python3
"""Fail a PR that mints a new legacy-named thing.

Hard rule 7 of the sunset plan: never mint anything new carrying the old brand. A
service, secret, topic, env var, file or identifier named that way adds a
redirect somebody has to keep forever and spends a rename option that was already
paid for. The programme runs for weeks with ordinary feature work alongside it,
so the rule needs a gate rather than a reviewer's attention.

What it does: counts the lines carrying the legacy name per file, in the tree being
built and in the base tree, and fails on any file that went **up**. Decreases are
the point of the programme and are reported as progress.

Why per file rather than a repo total: a total hides an addition behind an
unrelated deletion elsewhere in the same PR, while a per-file count keeps a
within-file move (delete plus re-add) at net zero, which is most of what the
infrastructure and rewrite waves do.

Why against the base tree rather than a committed baseline: a baseline file goes
stale, churns on every move, and has to be regenerated by the same person the
gate is pointed at. On a ``pull_request`` the checkout is already the merge
commit, so the comparison against ``main`` is exactly this PR's contribution and
there is nothing to maintain.

**The escape hatch.** A line carrying the marker ``legacy-name-ok`` is not
counted. Rule 3 keeps old names readable forever, so legitimate additions exist:
a compat alias, a redirect, a test pinning the old wire format. Put the marker on
the line with a reason and it lands in the diff where a reviewer will see it.

**What this does not enforce.** Marking an EXISTING line exempt frees a slot,
which a new unmarked line in the same file can then fill: non-exempt flat, gate
passes. That is not fixable by counting — legitimately adding one marked alias
has the identical signature per file (non-exempt flat, exempt +1, total +1),
because the difference is which line carries the marker, not how many do. Every
newly exempted line is therefore printed, on the passing path as well, so the one
move that buys headroom can never be made quietly.

Usage::

    scripts/legacy_name_ratchet.py                     # compare against origin/main
    scripts/legacy_name_ratchet.py --base <tree-ish>
    scripts/legacy_name_ratchet.py --report            # counts only, never fails
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import Counter

# The legacy brand. Matched case-insensitively, so every casing in the tree
# counts — prose, identifiers and SCREAMING_SNAKE env names alike. This is the
# only place the literal appears in this file, and it carries the marker so the
# gate does not trip over its own pattern; excluding the file instead would leave
# a hole in the scan.
LEGACY_NAME = "memclaw"  # legacy-name-ok: the pattern this gate searches for

# Kept deliberately ugly so it is never typed by accident and always reads as a
# decision rather than a formatting artifact.
EXEMPT_MARKER = "legacy-name-ok"

# Matched as a bounded token, not a bare substring. A substring test exempts any
# line that merely contains the marker inside a longer word — "not
# legacy-name-okay to leave in" would silence a real occurrence, which is a hole
# in the gate rather than a nuisance. Case-insensitive for the same reason the
# name match is: a marker typed ``Legacy-Name-OK`` is plainly a decision, and
# failing it would be a spurious red on a line someone deliberately annotated.
#
# Bounded on BOTH sides, and the two are not the same check: the lookahead stops
# ``legacy-name-okay`` and the lookbehind stops ``somelegacy-name-ok``. Either one
# alone leaves the hole open from the other end.
#
# Neither boundary is a comment prefix — comment syntax differs across the file
# types this scans, and JSON has none at all while still being somewhere an alias
# can legitimately live.
EXEMPT_RE = re.compile(rf"(?<![\w-]){re.escape(EXEMPT_MARKER)}(?=[\s:]|$)", re.IGNORECASE)


def _git(args: list[str]) -> str:
    """git, with ``grep``'s no-match exit treated as an empty result.

    ``git grep`` exits 1 when nothing matched, which is the ordinary outcome for a
    clean tree rather than an error; a bad tree-ish exits 128 and is raised, so a
    mistyped base cannot read as "no matches" and quietly pass the gate.

    What exit 1 does NOT distinguish is a pathspec that matches nothing — git
    reports that the same way, with an empty stderr. That is why
    :func:`main` refuses to pass when BOTH trees come back empty.
    """
    # check=False deliberately: the return code is the signal here, not an error.
    proc = subprocess.run(args, capture_output=True, text=True, check=False)
    if proc.returncode == 0:
        return proc.stdout
    if proc.returncode == 1:
        return ""
    raise RuntimeError(f"{' '.join(args)} failed ({proc.returncode}): {proc.stderr.strip()}")


def _grep(tree: str | None, pathspec: str = ":/") -> list[tuple[str, str, str, bool]]:
    """``(path, lineno, text, exempt)`` for every matching line.

    Exempt lines are returned rather than dropped so the caller can report what a
    change newly exempted — see :func:`main`.

    ``tree=None`` reads the working tree. ``-I`` skips binary files. ``--full-name``
    makes paths repo-relative whatever the working directory, which the ``:/``
    pathspec then matches against the whole repo rather than a subtree.

    ``-z`` is what makes the parse safe rather than merely usually-right. Without
    it the record is colon-separated and a colon in either the path (legal on
    Linux, which is what CI runs on) or the matched text shifts every field after
    it: the line is attributed to a path that does not exist, the real file's
    count never rises, and the gate passes while appearing to work. With ``-z``
    the fields are NUL-separated and only the ``<tree>:`` prefix is colon-joined —
    and that one is a string this function passed in, so it can be stripped by
    length instead of by searching.
    """
    args = ["git", "grep", "-I", "-i", "-n", "-z", "--full-name", "-e", LEGACY_NAME]
    if tree is not None:
        args.append(tree)
    args += ["--", pathspec]

    prefix = f"{tree}:" if tree is not None else ""

    out: list[tuple[str, str, str, bool]] = []
    # Records are newline-terminated (a matched line cannot contain one) and
    # their three fields are NUL-separated.
    for record in _git(args).split("\n"):
        if not record:
            continue
        parts = record.split("\0", 2)
        if len(parts) != 3:
            continue
        path, lineno, text = parts
        if prefix:
            if not path.startswith(prefix):
                continue
            path = path[len(prefix) :]
        out.append((path, lineno, text, bool(EXEMPT_RE.search(text))))
    return out


def _literal(path: str) -> str:
    """A pathspec that means exactly this path.

    The same hazard one level up: a bare path is interpreted as a pathspec, so one
    containing ``*``, ``?`` or a leading ``:`` would match the wrong files or be
    read as pathspec magic. ``:(literal)`` disables both.
    """
    return f":(literal){path}"


def counts(tree: str | None) -> Counter[str]:
    """Non-exempt lines per file — what the ratchet holds flat."""
    return Counter(path for path, _, _, exempt in _grep(tree) if not exempt)


def exempt_counts(tree: str | None) -> Counter[str]:
    """Exempt lines per file — reported, never gated on. See :func:`main`."""
    return Counter(path for path, _, _, exempt in _grep(tree) if exempt)


def _report_new_exemptions(base: str) -> None:
    """Name every line this change newly exempted, whether or not it fails.

    The one thing a count-based ratchet cannot decide for itself. Marking an
    existing line exempt lowers a file's non-exempt count by one, which is exactly
    enough headroom to add a new unmarked occurrence in the same file and come out
    flat. The gate passes, and a real addition got through.

    No count separates that from the legitimate case, and this is not a
    limitation of the implementation. Both look identical per file — non-exempt
    flat, exempt up one, total up one — because the difference is *which* line
    carries the marker, not how many do. Line identity would decide it, and line
    identity is defeated by editing the text.

    So it is reported instead of adjudicated: an exemption is the one move that
    buys headroom, so no PR should be able to make one quietly. Printed on the
    passing path too, because that is the path the swap takes.
    """
    before, after = exempt_counts(base), exempt_counts(None)
    added = {p: n - before.get(p, 0) for p, n in after.items() if n > before.get(p, 0)}
    if not added:
        return

    total = sum(added.values())
    print(f"{total} line(s) newly exempted in {len(added)} file(s) — check each one is a")
    print("compat alias, a redirect or a pinned wire format, and not headroom for a new name:")
    for path in sorted(added):
        for _, lineno, text, exempt in _grep(None, pathspec=_literal(path)):
            if exempt:
                print(f"  {path}:{lineno}: {text.strip()[:100]}")
    print()


def main() -> int:
    parser = argparse.ArgumentParser(description="Ratchet on lines carrying the legacy brand.")
    parser.add_argument("--base", default="origin/main", help="tree-ish to compare against")
    parser.add_argument("--report", action="store_true", help="print counts and exit 0")
    args = parser.parse_args()

    head = counts(None)

    if args.report:
        print(f"{sum(head.values())} lines across {len(head)} files")
        for path, n in sorted(head.items(), key=lambda kv: (-kv[1], kv[0])):
            print(f"  {n:>4}  {path}")
        return 0

    base = counts(args.base)

    if not head and not base:
        # A pathspec that matches nothing exits 1 with an empty stderr, exactly
        # like a clean tree — so a broken scan reads as "nothing to report" and
        # the gate passes every PR from then on, silently, for the rest of the
        # programme. Both trees empty is either that or a finished migration,
        # and both want a human.
        print(
            f"Found no '{LEGACY_NAME}' lines in either tree.\n"
            "Either the pattern or the pathspec is broken — in which case this gate has\n"
            "been passing without checking anything — or the migration is complete and\n"
            "this gate should be deleted along with the last of the old names."
        )
        return 1

    _report_new_exemptions(args.base)

    grown = {p: (base.get(p, 0), n) for p, n in head.items() if n > base.get(p, 0)}

    if not grown:
        removed = sum(max(0, c - head.get(p, 0)) for p, c in base.items())
        net = sum(head.values()) - sum(base.values())
        print(
            f"No new lines. {removed} removed by this change ({net:+d} net)."
            if removed
            else "No new lines."
        )
        return 0

    print(f"This change adds the legacy name in {len(grown)} file(s).\n")
    for path, (before, after) in sorted(grown.items()):
        print(f"  {path}  ({before} -> {after})")
        for _, lineno, text, exempt in _grep(None, pathspec=_literal(path)):
            if not exempt:
                print(f"      {lineno}: {text.strip()[:110]}")
    print(
        f"\nRule 7 of the sunset plan: mint nothing new named '{LEGACY_NAME}'. Every one adds a\n"
        "redirect to keep forever and spends a rename option. Use the Caura name instead.\n\n"
        "If the addition is deliberate — a compat alias, a redirect, a test pinning the old\n"
        f"wire format, all of which rule 3 requires — append '{EXEMPT_MARKER}: <reason>' to the\n"
        "line. It is then exempt, and the reason is visible in the diff."
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
