#!/usr/bin/env python3
"""Fail a PR that mints a new legacy-named thing.

Hard rule 7 of the sunset plan: never mint anything new carrying the old brand. A
service, secret, topic, env var, file or identifier named that way adds a
redirect somebody has to keep forever and spends a rename option that was already
paid for. The programme runs for weeks with ordinary feature work alongside it,
so the rule needs a gate rather than a reviewer's attention.

What it does: counts the lines carrying the legacy name per file, in the tree being
built and in the base tree, and fails on any file that went **up**. Decreases are
the point of the programme and are reported as progress.

Why per file rather than a repo total: a total hides an addition behind an
unrelated deletion elsewhere in the same PR, while a per-file count keeps a
within-file move (delete plus re-add) at net zero, which is most of what the
infrastructure and rewrite waves do.

A move BETWEEN files is kept at net zero too, and needs a second check to be —
the per-file count alone fails it, because the destination goes up. So a line
whose exact text the base tree already had somewhere is treated as moved rather
than minted. See :func:`_minted`.

Why against the base tree rather than a committed baseline: a baseline file goes
stale, churns on every move, and has to be regenerated by the same person the
gate is pointed at. On a ``pull_request`` the checkout is already the merge
commit, so the comparison against ``main`` is exactly this PR's contribution and
there is nothing to maintain.

**The escape hatch.** A line carrying the marker ``legacy-name-ok`` is not
counted. Rule 3 keeps old names readable forever, so legitimate additions exist:
a compat alias, a redirect, a test pinning the old wire format. Put the marker on
the line with a reason and it lands in the diff where a reviewer will see it.

**Why the count is not the check.** A file's total is a cheap proxy for "worth
looking at", and it is the wrong one in both directions. It fails a cross-file
move, where the destination rises and nothing was minted. And it passes a
same-file swap, where one branded line is dropped and a different, brand-new one
added in the same edit: flat total, so a count-first filter never looks at the
text and the gate reports "No new lines." Both are decided by comparing the text
instead, which is what :func:`_minted` does for every file rather than only the
ones whose tally rose.

That also closes the exempt-and-add swap, which counting genuinely cannot: mark
an existing line exempt and fill the freed slot with a new unmarked one and every
tally matches a legitimate marked alias — non-exempt flat, exempt +1, total +1 —
because the difference is *which* line carries the marker. The texts differ
though. A legitimate alias adds new EXEMPT text and no new non-exempt text, so
there is nothing to charge; the swap adds non-exempt text the repo never had.
Every newly exempted line is still printed, on the passing path too, because the
report is what made the hole visible and stays useful when the swap is deliberate.

**What this still does not enforce.** The move check pairs an addition with a
deletion by text, so it cannot know the two are the same line: adding a genuinely
new occurrence while coincidentally deleting a byte-identical one elsewhere comes
out flat and is excused. That one is identical in every number AND in every text,
so nothing here can decide it — every excused move is printed with the file whose
deletion paid for it, and a reviewer who sees an unrelated file there has found
the laundering.

Usage::

    scripts/legacy_name_ratchet.py                     # compare against origin/main
    scripts/legacy_name_ratchet.py --base <tree-ish>
    scripts/legacy_name_ratchet.py --report            # counts only, never fails
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import Counter
from typing import NamedTuple

# The legacy brand. Matched case-insensitively, so every casing in the tree
# counts — prose, identifiers and SCREAMING_SNAKE env names alike. This is the
# only place the literal appears in this file, and it carries the marker so the
# gate does not trip over its own pattern; excluding the file instead would leave
# a hole in the scan.
LEGACY_NAME = "memclaw"  # legacy-name-ok: the pattern this gate searches for

# Kept deliberately ugly so it is never typed by accident and always reads as a
# decision rather than a formatting artifact.
EXEMPT_MARKER = "legacy-name-ok"

# Matched as a bounded token, not a bare substring. A substring test exempts any
# line that merely contains the marker inside a longer word — "not
# legacy-name-okay to leave in" would silence a real occurrence, which is a hole
# in the gate rather than a nuisance. Case-insensitive for the same reason the
# name match is: a marker typed ``Legacy-Name-OK`` is plainly a decision, and
# failing it would be a spurious red on a line someone deliberately annotated.
#
# Bounded on BOTH sides, and the two are not the same check: the lookahead stops
# ``legacy-name-okay`` and the lookbehind stops ``somelegacy-name-ok``. Either one
# alone leaves the hole open from the other end.
#
# Neither boundary is a comment prefix — comment syntax differs across the file
# types this scans, and JSON has none at all while still being somewhere an alias
# can legitimately live.
EXEMPT_RE = re.compile(
    rf"(?<![\w-]){re.escape(EXEMPT_MARKER)}(?=[\s:]|$)", re.IGNORECASE
)


# Above this many lines sharing one reason, the list is collapsed to a count.
# Four is where a homogeneous block stops being read line by line; below it the
# individual lines are still the more useful form.
_EXEMPTION_GROUP_AT = 4


def _git(args: list[str]) -> str:
    """git, with ``grep``'s no-match exit treated as an empty result.

    ``git grep`` exits 1 when nothing matched, which is the ordinary outcome for a
    clean tree rather than an error; a bad tree-ish exits 128 and is raised, so a
    mistyped base cannot read as "no matches" and quietly pass the gate.

    What exit 1 does NOT distinguish is a pathspec that matches nothing — git
    reports that the same way, with an empty stderr. That is why
    :func:`main` refuses to pass when BOTH trees come back empty.
    """
    # check=False deliberately: the return code is the signal here, not an error.
    proc = subprocess.run(args, capture_output=True, text=True, check=False)
    if proc.returncode == 0:
        return proc.stdout
    if proc.returncode == 1:
        return ""
    raise RuntimeError(
        f"{' '.join(args)} failed ({proc.returncode}): {proc.stderr.strip()}"
    )


def _grep(tree: str | None, pathspec: str = ":/") -> list[tuple[str, str, str, bool]]:
    """``(path, lineno, text, exempt)`` for every matching line.

    Exempt lines are returned rather than dropped so the caller can report what a
    change newly exempted — see :func:`main`.

    ``tree=None`` reads the working tree. ``-I`` skips binary files. ``--full-name``
    makes paths repo-relative whatever the working directory, which the ``:/``
    pathspec then matches against the whole repo rather than a subtree.

    ``-z`` is what makes the parse safe rather than merely usually-right. Without
    it the record is colon-separated and a colon in either the path (legal on
    Linux, which is what CI runs on) or the matched text shifts every field after
    it: the line is attributed to a path that does not exist, the real file's
    count never rises, and the gate passes while appearing to work. With ``-z``
    the fields are NUL-separated and only the ``<tree>:`` prefix is colon-joined —
    and that one is a string this function passed in, so it can be stripped by
    length instead of by searching.
    """
    args = ["git", "grep", "-I", "-i", "-n", "-z", "--full-name", "-e", LEGACY_NAME]
    if tree is not None:
        args.append(tree)
    args += ["--", pathspec]

    prefix = f"{tree}:" if tree is not None else ""

    out: list[tuple[str, str, str, bool]] = []
    # Records are newline-terminated (a matched line cannot contain one) and
    # their three fields are NUL-separated.
    for record in _git(args).split("\n"):
        if not record:
            continue
        parts = record.split("\0", 2)
        if len(parts) != 3:
            continue
        path, lineno, text = parts
        if prefix:
            if not path.startswith(prefix):
                continue
            path = path[len(prefix) :]
        out.append((path, lineno, text, bool(EXEMPT_RE.search(text))))
    return out


def _added_lines(base: str, path: str) -> set[int]:
    """Line numbers this change actually added to ``path``, per git's own diff.

    Used for the failure report only, never for the decision. The decision
    compares text because a per-line diff calls every move an addition — but the
    report has the opposite problem, and needs exactly what the diff knows.

    Without it the report spends a text-keyed budget in file order, which assumes
    the first occurrence of a text is the new one. Line order says nothing about
    that. A file holding an untouched line and a new line with identical text
    gets the untouched one named, and the real addition is never printed — the
    reader is sent to a line that has not changed, for a gate whose whole output
    is "here is the line you added".

    Empty on any failure, and the caller falls back to naming every occurrence of
    the minted text: too many lines is a nuisance, none is a dead end.
    """
    try:
        out = _git(["git", "diff", "-U0", base, "--", _literal(path)])
    except RuntimeError:
        return set()

    added: set[int] = set()
    lineno = 0
    for line in out.splitlines():
        if line.startswith("@@"):
            # ``@@ -a,b +c,d @@`` — c is where the added run starts.
            match = re.search(r"\+(\d+)", line)
            lineno = int(match.group(1)) if match else 0
        elif line.startswith("+") and not line.startswith("+++"):
            added.add(lineno)
            lineno += 1
    return added


def _literal(path: str) -> str:
    """A pathspec that means exactly this path.

    The same hazard one level up: a bare path is interpreted as a pathspec, so one
    containing ``*``, ``?`` or a leading ``:`` would match the wrong files or be
    read as pathspec magic. ``:(literal)`` disables both.
    """
    return f":(literal){path}"


class Scan(NamedTuple):
    """One pass over a tree, and everything the gate needs from it.

    ``by_file`` maps path to the text of its non-exempt matching lines and how
    many times each appears; ``total`` is the same tally repo-wide; ``exempt``
    counts marked lines per file, which are reported but never gated on.

    Text is whitespace-stripped. A line that moves into a class body or a deeper
    block gets re-indented on the way, and an indentation-sensitive comparison
    would call that new text. What is being compared is whether the repo already
    had this name written this way, which indentation does not change.

    One scan rather than three: the counts the ratchet holds flat are just
    ``sum(by_file[path].values())``, so deriving them here keeps a single
    definition of "a line that counts" instead of the same rule written out in
    three places that have to agree.
    """

    by_file: dict[str, Counter[str]]
    total: Counter[str]
    exempt: Counter[str]

    def counts(self) -> Counter[str]:
        """Non-exempt lines per file — what the ratchet holds flat."""
        return Counter({path: sum(c.values()) for path, c in self.by_file.items()})


def scan(tree: str | None) -> Scan:
    """Read a tree once. ``tree=None`` is the working tree."""
    by_file: dict[str, Counter[str]] = {}
    total: Counter[str] = Counter()
    exempt: Counter[str] = Counter()
    for path, _, text, is_exempt in _grep(tree):
        if is_exempt:
            exempt[path] += 1
            continue
        stripped = text.strip()
        by_file.setdefault(path, Counter())[stripped] += 1
        total[stripped] += 1
    return Scan(by_file, total, exempt)


def _mint_budget(head_total: Counter[str], base_total: Counter[str]) -> Counter[str]:
    """How many of each text the repo actually gained — the whole charge available.

    Computed once for the run and spent down by :func:`_minted`, because the
    charge is a repo-wide quantity and the files that can claim it are counted
    one at a time. Recomputing it per file hands every destination the same
    budget: delete one copy of a line from A, add one to each of B and C, and
    both B and C independently look like the only mint of a text the repo gained
    once — two failures reported for one addition, and one of them a move.
    """
    return +Counter(
        {text: n - base_total.get(text, 0) for text, n in head_total.items()}
    )


def _minted(
    path: str,
    head_by_file: dict[str, Counter[str]],
    base_by_file: dict[str, Counter[str]],
    budget: Counter[str],
) -> tuple[Counter[str], Counter[str]]:
    """``(minted, moved)`` for ``path``: text the repo did not have, and text it did.

    Spends ``budget`` — see :func:`_mint_budget`. Callers must iterate paths in a
    stable order: when a text lands in several files and the repo gained fewer
    copies than that, which destination is charged is arbitrary but the count is
    not, and an arbitrary-but-unstable answer would flake.

    Per-file counting is right and the module docstring's defence of it stands: a
    repo total hides a real addition behind an unrelated deletion elsewhere. But
    it only keeps a move at net zero *within* one file. Move a branded line from
    A to B and B goes ``0 -> 1`` while A drops, so the gate fails a change that
    minted nothing (#882).

    That mattered more than the spurious red, because the remedy the failure text
    offered was an exemption, and none of the three reasons rule 3 recognises —
    compat alias, redirect, pinned wire format — describes a move. The only way
    past the gate was to write a reason that was not true, into the one
    annotation whose whole value is that its reasons are true.

    So a move is recognised here rather than annotated away. A line is a move
    when the repo-wide count of that exact text did not go up: the name existed,
    in those words, and now sits somewhere else. It is minted when the count did
    go up, which no rearrangement can produce. Both shapes are covered, including
    a line moving between two files that both already exist — the likelier shape
    during a consolidation wave, and the one ``--find-renames`` cannot see.

    Strictness is unchanged for genuinely new text: a new name has no matching
    deletion to pair with, so its repo-wide count rises and it fails.

    **What text-matching cannot decide, and why it is reported instead.** The
    pairing is by text, not by provenance — nothing here knows that the deletion
    it paired with is the *same* line. A change that adds a genuinely new
    occurrence in one file while coincidentally deleting a byte-identical line
    somewhere unrelated comes out flat, and the new one is excused.

    No count fixes that, for the same reason the exempt-and-add swap below is not
    fixable: the two cases are identical in every number, and differ only in
    intent. ``--find-renames`` does not settle it either — it answers a narrower
    question and misses the common shape entirely.

    So it takes the same answer as the swap: every excused move is printed, on
    the passing path, with the base file whose deletion paid for it. A laundered
    mint stays visible in the CI log even though the gate passes, which is the
    most a text comparison can honestly offer.
    """
    new_here = head_by_file.get(path, Counter()) - base_by_file.get(path, Counter())

    minted: Counter[str] = Counter()
    moved: Counter[str] = Counter()
    for text, added_here in sorted(new_here.items()):
        # A file can gain two copies of a line the repo only gained one of: one
        # moved in, one is new. Split the tally rather than picking a side, and
        # take the charge out of the shared budget so the next file cannot be
        # charged for the same addition.
        charge = min(added_here, budget[text])
        budget[text] -= charge
        minted[text] = charge
        moved[text] = added_here - charge
    return +minted, +moved  # unary plus drops the zero entries


def _report_excused_moves(
    excused: dict[str, Counter[str]],
    base_by_file: dict[str, Counter[str]],
    head_by_file: dict[str, Counter[str]],
) -> None:
    """Name every line the move check let through, and what paid for it.

    The counterpart to :func:`_report_new_exemptions`, for the same reason and
    with the same honesty. Pairing an addition with a deletion by text cannot
    know the two are the same line, so a change that adds a genuinely new
    occurrence while coincidentally deleting a byte-identical one elsewhere comes
    out flat and is excused. No count separates that from a real move — they are
    identical in every number — so it is reported rather than adjudicated.

    Printed on the passing path, because passing is the only path this takes.
    Naming the base file whose deletion paid for each one is what makes it
    checkable: a reviewer who sees an unrelated file named there has found a
    laundered mint, and nothing else in CI would have shown it.

    A source is a file whose count of that text actually WENT DOWN, not merely
    one that had it. Every file holding an unchanged copy also contains the text,
    so listing on containment names bystanders as sources — and since the list is
    truncated, an alphabetically earlier bystander can push the real source out of
    view entirely. That turns the one output a reviewer is meant to check into
    noise, which is worse than not printing it.
    """
    if not excused:
        return

    total = sum(sum(c.values()) for c in excused.values())
    print(f"{total} line(s) treated as moved rather than added — the same text left")
    print(
        "another file in this change. Check the pairing is real and not a coincidence:"
    )
    for path in sorted(excused):
        for text, n in sorted(excused[path].items()):
            came_from = sorted(
                p
                for p, c in base_by_file.items()
                if p != path and c[text] > head_by_file.get(p, Counter())[text]
            )
            origin = ", ".join(came_from[:3]) or "an unknown file"
            if len(came_from) > 3:
                origin += f" (+{len(came_from) - 3} more)"
            print(f"  {path}: {'x' + str(n) + ' ' if n > 1 else ''}{text[:80]}")
            print(f"      was in: {origin}")
    print()


def _report_new_exemptions(before: Counter[str], after: Counter[str]) -> None:
    """Name every line this change newly exempted, whether or not it fails.

    The one thing a count-based ratchet cannot decide for itself, and the reason
    this report exists. Marking an existing line exempt lowers a file's
    non-exempt count by one, which is exactly enough headroom to add a new
    unmarked occurrence in the same file and come out flat.

    No count separates that from the legitimate case. Both look identical per
    file — non-exempt flat, exempt up one, total up one — because the difference
    is *which* line carries the marker, not how many do.

    The **texts** are not identical, though, and since :func:`_minted` compares
    those the swap now fails rather than passing quietly: a legitimate alias adds
    exempt text and nothing chargeable, while the swap adds non-exempt text the
    repo never had. This report is no longer the only thing standing between that
    move and a green tick.

    It is still printed, on the passing path as well. An exemption is the move
    that buys headroom, and a deliberate one — an alias landing in the same PR as
    unrelated work — should never be made quietly even when it is legitimate.
    """
    added = {p: n - before.get(p, 0) for p, n in after.items() if n > before.get(p, 0)}
    if not added:
        return

    total = sum(added.values())
    print(
        f"{total} line(s) newly exempted in {len(added)} file(s) — check each one is a"
    )
    print(
        "compat alias, a redirect or a pinned wire format, and not headroom for a new name:"
    )

    # Grouped by reason, because the wall is the failure mode. A dual-read wave
    # exempts dozens of lines carrying one identical reason, and at that length
    # the list stops being read — which costs exactly the thing it is for, since
    # the swap this report exists to expose shows up as the ONE reason that does
    # not match its neighbours. Collapsing the repeats is what makes the odd one
    # visible instead of burying it on line forty.
    by_reason: dict[str, list[tuple[str, str, str]]] = {}
    for path in sorted(added):
        for _, lineno, text, exempt in _grep(None, pathspec=_literal(path)):
            if not exempt:
                continue
            stripped = text.strip()
            match = EXEMPT_RE.search(stripped)
            tail = stripped[match.end() :].lstrip(": ") if match else ""
            by_reason.setdefault(tail.strip() or "(no reason given)", []).append(
                (path, lineno, stripped)
            )

    for reason, lines in sorted(by_reason.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        if len(lines) <= _EXEMPTION_GROUP_AT:
            for path, lineno, stripped in lines:
                print(f"  {path}:{lineno}: {stripped[:100]}")
            continue
        files = sorted({path for path, _, _ in lines})
        shown = ", ".join(files[:4]) + (
            f" (+{len(files) - 4} more)" if len(files) > 4 else ""
        )
        print(f"  {len(lines)}x  {reason[:80]}")
        print(f"      in {len(files)} file(s): {shown}")
    print()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Ratchet on lines carrying the legacy brand."
    )
    parser.add_argument(
        "--base", default="origin/main", help="tree-ish to compare against"
    )
    parser.add_argument("--report", action="store_true", help="print counts and exit 0")
    args = parser.parse_args()

    # Both scans under one guard. A bad ``--base`` is the likely cause, but the
    # working-tree scan reaches git the same way and can fail the same way, and
    # leaving it bare would surface that as a traceback and exit 1 — which in this
    # script means "ran, found new names". A gate that cannot run must never be
    # mistaken for a gate that failed you. Exit 2 says it could not run.
    try:
        head_scan = scan(None)
        if args.report:
            head = head_scan.counts()
            print(f"{sum(head.values())} lines across {len(head)} files")
            for path, n in sorted(head.items(), key=lambda kv: (-kv[1], kv[0])):
                print(f"  {n:>4}  {path}")
            return 0
        base_scan = scan(args.base)
    except RuntimeError as exc:
        print(exc, file=sys.stderr)
        return 2

    head, base = head_scan.counts(), base_scan.counts()

    if not head and not base:
        # A pathspec that matches nothing exits 1 with an empty stderr, exactly
        # like a clean tree — so a broken scan reads as "nothing to report" and
        # the gate passes every PR from then on, silently, for the rest of the
        # programme. Both trees empty is either that or a finished migration,
        # and both want a human.
        print(
            f"Found no '{LEGACY_NAME}' lines in either tree.\n"
            "Either the pattern or the pathspec is broken — in which case this gate has\n"
            "been passing without checking anything — or the migration is complete and\n"
            "this gate should be deleted along with the last of the old names."
        )
        return 1

    _report_new_exemptions(base_scan.exempt, head_scan.exempt)

    head_by_file, base_by_file = head_scan.by_file, base_scan.by_file
    budget = _mint_budget(head_scan.total, base_scan.total)

    grown = {}
    excused: dict[str, Counter[str]] = {}
    # Sorted: the budget is spent as files are visited, so the order decides which
    # destination is charged when one text lands in several. Arbitrary is fine;
    # unstable is not.
    for path in sorted(head):
        before, n = base.get(path, 0), head[path]
        # Deliberately NOT gated on ``n > before``. A file that drops one branded
        # line and adds a different, brand-new one in the same edit comes out
        # flat, and a count-first filter skips it before anything looks at the
        # text — so the new name is never surfaced and the gate reports "No new
        # lines." Comparing the text is what catches it; the count was only ever
        # a cheap proxy for "worth looking at", and it is the wrong one.
        minted, moved = _minted(path, head_by_file, base_by_file, budget)
        if moved:
            excused[path] = moved
        if minted:
            grown[path] = (before, n, minted)

    _report_excused_moves(excused, base_by_file, head_by_file)

    if not grown:
        removed = sum(max(0, c - head.get(p, 0)) for p, c in base.items())
        net = sum(head.values()) - sum(base.values())
        print(
            f"No new lines. {removed} removed by this change ({net:+d} net)."
            if removed
            else "No new lines."
        )
        return 0

    print(f"This change adds the legacy name in {len(grown)} file(s).\n")
    for path, (before, after, minted) in sorted(grown.items()):
        # A flat or falling count can still fail: what failed is the text, not the
        # tally, and saying so stops the reader arguing with the arithmetic. Flat
        # and falling are said separately because they are different sentences —
        # calling a count that dropped "unchanged" invites exactly the argument
        # the note exists to head off.
        if after > before:
            note = ""
        elif after == before:
            note = ", count unchanged — the text is new"
        else:
            note = ", count fell — the text is new"
        print(f"  {path}  ({before} -> {after}{note})")
        # Lines carrying minted text AND actually added by this change. Both
        # halves are needed. Without the text filter the report names every
        # branded line in the file; without the diff it names the first line
        # holding the text, which in a file that already had one is a line
        # nobody touched.
        added = _added_lines(args.base, path)
        candidates = [
            (lineno, text.strip())
            for _, lineno, text, exempt in _grep(None, pathspec=_literal(path))
            if not exempt and text.strip() in minted
        ]
        shown = [(n, t) for n, t in candidates if int(n) in added]
        # Falling back to every occurrence rather than to silence: if the diff
        # could not be read, too many lines is a nuisance and none is a dead end.
        shown = shown or candidates
        for lineno, stripped in shown:
            print(f"      {lineno}: {stripped[:110]}")

        # When a change adds several identical lines and only some are minted,
        # every one of them is a line this change added and they cannot be told
        # apart — that is what identical means. Naming one would be a guess
        # dressed as a finding, so all are printed and the split is stated.
        for text, new in sorted(minted.items()):
            here = sum(1 for _, t in shown if t == text)
            if here > new:
                print(
                    f"      ^ {here} added lines share this text; {new} new, "
                    f"{here - new} moved in from elsewhere — identical, so which is which"
                    " cannot be told apart"
                )
    print(
        f"\nRule 7 of the sunset plan: mint nothing new named '{LEGACY_NAME}'. Every one adds a\n"
        "redirect to keep forever and spends a rename option. Use the Caura name instead.\n\n"
        "A line moved here from another file is not this: text the base tree already\n"
        "had somewhere is recognised as a move and does not fail. Every line above is\n"
        "text this repo did not have before, so no rearrangement produced it.\n\n"
        "If the addition is deliberate — a compat alias, a redirect, a test pinning the old\n"
        f"wire format, all of which rule 3 requires — append '{EXEMPT_MARKER}: <reason>' to the\n"
        "line. It is then exempt, and the reason is visible in the diff."
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
